### ISSUE TITLE
[Python] 리스트 슬라이싱

### ISSUE THREAD

**Issue by lsj0822** [4Moyede/HexatonClass-01#108]
**Content** :

```python
airbnb_remake = airbnb_db.loc[:, ['room_type','neighborhood':'minstay']]
airbnb_remake
```

다음과 같이 3번 문제에서 필요한 column만을 불러올때, 이때 필요한 칼럼이 2번째와 4~11번째기 때문에 8개의 칼럼을 일일히 불러오는건 너무 지저분해보여 다음과 같이 불러왔는데, 당연히 오류가 생겼습니다... 그런데, 여기에서 콜론(:)을 제거해보니 정상적으로 코드가 돌아가는 것을 확인할 수 있었습니다!

콜론을 사용하는 경우, 다음과 같이 콤마(,)와 혼용하여 쓸수는 없는건가요?? 아니면 다른 방법으로 사용할 수 있는건가요??

**Comment by yoomambo** [comment]
> **Content** :
> 
> ```python
> airbnb_remake = airbnb_db.loc[:, ['room_type','neighborhood':'minstay']]
> airbnb_remake
> ```
> 
> 다음과 같이 3번 문제에서 필요한 column만을 불러올때, 이때 필요한 칼럼이 2번째와 4~11번째기 때문에 8개의 칼럼을 일일히 불러오는건 너무 지저분해보여 다음과 같이 불러왔는데, 당연히 오류가 생겼습니다... 그런데, 여기에서 콜론(:)을 제거해보니 정상적으로 코드가 돌아가는 것을 확인할 수 있었습니다!
> 
> 콜론을 사용하는 경우, 다음과 같이 콤마(,)와 혼용하여 쓸수는 없는건가요?? 아니면 다른 방법으로 사용할 수 있는건가요??

```python
airbnb_remake = airbnb_db.loc[:, ['room_type','neighborhood':'minstay']]
airbnb_remake
```

이 부분에서 성준 멘티님이 궁금해하는 : 콜론이 loc 뒤에있는 콜론일까요 아니면 neighborhood 뒤에있는 콜론일까요?

**Comment by lsj0822** [comment]
> > **Content** :
> > ```python
> > airbnb_remake = airbnb_db.loc[:, ['room_type','neighborhood':'minstay']]
> > airbnb_remake
> > ```
> > 
> > 
> > 다음과 같이 3번 문제에서 필요한 column만을 불러올때, 이때 필요한 칼럼이 2번째와 4~11번째기 때문에 8개의 칼럼을 일일히 불러오는건 너무 지저분해보여 다음과 같이 불러왔는데, 당연히 오류가 생겼습니다... 그런데, 여기에서 콜론(:)을 제거해보니 정상적으로 코드가 돌아가는 것을 확인할 수 있었습니다!
> > 콜론을 사용하는 경우, 다음과 같이 콤마(,)와 혼용하여 쓸수는 없는건가요?? 아니면 다른 방법으로 사용할 수 있는건가요??
> 
> ```python
> airbnb_remake = airbnb_db.loc[:, ['room_type','neighborhood':'minstay']]
> airbnb_remake
> ```
> 
> 이 부분에서 성준 멘티님이 궁금해하는 : 콜론이 loc 뒤에있는 콜론일까요 아니면 neighborhood 뒤에있는 콜론일까요?



> > **Content** :
> > ```python
> > airbnb_remake = airbnb_db.loc[:, ['room_type','neighborhood':'minstay']]
> > airbnb_remake
> > ```
> > 
> > 
> > 다음과 같이 3번 문제에서 필요한 column만을 불러올때, 이때 필요한 칼럼이 2번째와 4~11번째기 때문에 8개의 칼럼을 일일히 불러오는건 너무 지저분해보여 다음과 같이 불러왔는데, 당연히 오류가 생겼습니다... 그런데, 여기에서 콜론(:)을 제거해보니 정상적으로 코드가 돌아가는 것을 확인할 수 있었습니다!
> > 콜론을 사용하는 경우, 다음과 같이 콤마(,)와 혼용하여 쓸수는 없는건가요?? 아니면 다른 방법으로 사용할 수 있는건가요??
> 
> ```python
> airbnb_remake = airbnb_db.loc[:, ['room_type','neighborhood':'minstay']]
> airbnb_remake
> ```
> 
> 이 부분에서 성준 멘티님이 궁금해하는 : 콜론이 loc 뒤에있는 콜론일까요 아니면 neighborhood 뒤에있는 콜론일까요?

['room_type', neighborhood' : 'minstay'] 이 부분입니다!

**Comment by lsj0822** [comment]
> > > **Content** :
> > > ```python
> > > airbnb_remake = airbnb_db.loc[:, ['room_type','neighborhood':'minstay']]
> > > airbnb_remake
> > > ```
> > > 
> > > 
> > > 다음과 같이 3번 문제에서 필요한 column만을 불러올때, 이때 필요한 칼럼이 2번째와 4~11번째기 때문에 8개의 칼럼을 일일히 불러오는건 너무 지저분해보여 다음과 같이 불러왔는데, 당연히 오류가 생겼습니다... 그런데, 여기에서 콜론(:)을 제거해보니 정상적으로 코드가 돌아가는 것을 확인할 수 있었습니다!
> > > 콜론을 사용하는 경우, 다음과 같이 콤마(,)와 혼용하여 쓸수는 없는건가요?? 아니면 다른 방법으로 사용할 수 있는건가요??
> > 
> > 
> > ```python
> > airbnb_remake = airbnb_db.loc[:, ['room_type','neighborhood':'minstay']]
> > airbnb_remake
> > ```
> > 
> > 
> > 이 부분에서 성준 멘티님이 궁금해하는 : 콜론이 loc 뒤에있는 콜론일까요 아니면 neighborhood 뒤에있는 콜론일까요?
> 
> > > **Content** :
> > > ```python
> > > airbnb_remake = airbnb_db.loc[:, ['room_type','neighborhood':'minstay']]
> > > airbnb_remake
> > > ```
> > > 
> > > 
> > > 다음과 같이 3번 문제에서 필요한 column만을 불러올때, 이때 필요한 칼럼이 2번째와 4~11번째기 때문에 8개의 칼럼을 일일히 불러오는건 너무 지저분해보여 다음과 같이 불러왔는데, 당연히 오류가 생겼습니다... 그런데, 여기에서 콜론(:)을 제거해보니 정상적으로 코드가 돌아가는 것을 확인할 수 있었습니다!
> > > 콜론을 사용하는 경우, 다음과 같이 콤마(,)와 혼용하여 쓸수는 없는건가요?? 아니면 다른 방법으로 사용할 수 있는건가요??
> > 
> > 
> > ```python
> > airbnb_remake = airbnb_db.loc[:, ['room_type','neighborhood':'minstay']]
> > airbnb_remake
> > ```
> > 
> > 
> > 이 부분에서 성준 멘티님이 궁금해하는 : 콜론이 loc 뒤에있는 콜론일까요 아니면 neighborhood 뒤에있는 콜론일까요?
> 
> ['room_type', neighborhood' : 'minstay'] 이 부분입니다!

스스로 코드를 써본결과,

우선 이 코드에서 'neighborhood' : 'minstay' 라는 부분의 경우 불러올 수가 없었으나, 이 부분은 다음과 같이 column을 문자열로 대체하는것이 아닌 iloc이라는 각 column과 row를 번호를 부여하여 추출하는 함수로 했더니 불러올 수는 있었습니다! 그렇지만 원래 의도한 것인 2번 + 4~10번을 한꺼번에 불러올 수는 없었는데요, 이를 간단한 리스트를 통해 확인해보니

```python
a = [1,2,3,4,5]
a[3:4],a[1]
```

다음과 같이 코딩했을때 결과가 ([4], 2)가 나왔습니다. 그런데 여기에서 4의 경우 리스트이고 2는 정수형에 해당하는데, 이렇게 나온 이유는 리스트를 slicing했을때의 결과는 리스트로 나오고, 인덱싱했을때는 문자열로 나오기때문에 이때 위에서 의도한대로 'room_type', neighborhood : minstay라는 항목은 리스트와 문자열을 더하는거라 계산이 안된다는 것을 확인했습니다.

따라서 원래 의도대로 만들기위해 아예 자료형을 모두 리스트로 바꾼다음 이를 대입하는 방법으로 사용하여

```python
column_extract = [2] + list(range(4,11))
airbnb_remake = airbnb_db.iloc[:, column_extract]
```

와 같이 만들어서 해결했습니다

**Comment by lsj0822** [comment]
> > > > **Content** :
> > > > ```python
> > > > airbnb_remake = airbnb_db.loc[:, ['room_type','neighborhood':'minstay']]
> > > > airbnb_remake
> > > > ```
> > > > 
> > > > 
> > > > 다음과 같이 3번 문제에서 필요한 column만을 불러올때, 이때 필요한 칼럼이 2번째와 4~11번째기 때문에 8개의 칼럼을 일일히 불러오는건 너무 지저분해보여 다음과 같이 불러왔는데, 당연히 오류가 생겼습니다... 그런데, 여기에서 콜론(:)을 제거해보니 정상적으로 코드가 돌아가는 것을 확인할 수 있었습니다!
> > > > 콜론을 사용하는 경우, 다음과 같이 콤마(,)와 혼용하여 쓸수는 없는건가요?? 아니면 다른 방법으로 사용할 수 있는건가요??
> > > 
> > > 
> > > ```python
> > > airbnb_remake = airbnb_db.loc[:, ['room_type','neighborhood':'minstay']]
> > > airbnb_remake
> > > ```
> > > 
> > > 
> > > 이 부분에서 성준 멘티님이 궁금해하는 : 콜론이 loc 뒤에있는 콜론일까요 아니면 neighborhood 뒤에있는 콜론일까요?
> > 
> > 
> > > > **Content** :
> > > > ```python
> > > > airbnb_remake = airbnb_db.loc[:, ['room_type','neighborhood':'minstay']]
> > > > airbnb_remake
> > > > ```
> > > > 
> > > > 
> > > > 다음과 같이 3번 문제에서 필요한 column만을 불러올때, 이때 필요한 칼럼이 2번째와 4~11번째기 때문에 8개의 칼럼을 일일히 불러오는건 너무 지저분해보여 다음과 같이 불러왔는데, 당연히 오류가 생겼습니다... 그런데, 여기에서 콜론(:)을 제거해보니 정상적으로 코드가 돌아가는 것을 확인할 수 있었습니다!
> > > > 콜론을 사용하는 경우, 다음과 같이 콤마(,)와 혼용하여 쓸수는 없는건가요?? 아니면 다른 방법으로 사용할 수 있는건가요??
> > > 
> > > 
> > > ```python
> > > airbnb_remake = airbnb_db.loc[:, ['room_type','neighborhood':'minstay']]
> > > airbnb_remake
> > > ```
> > > 
> > > 
> > > 이 부분에서 성준 멘티님이 궁금해하는 : 콜론이 loc 뒤에있는 콜론일까요 아니면 neighborhood 뒤에있는 콜론일까요?
> > 
> > 
> > ['room_type', neighborhood' : 'minstay'] 이 부분입니다!
> 
> 스스로 코드를 써본결과,
> 
> 우선 이 코드에서 'neighborhood' : 'minstay' 라는 부분의 경우 불러올 수가 없었으나, 이 부분은 다음과 같이 column을 문자열로 대체하는것이 아닌 iloc이라는 각 column과 row를 번호를 부여하여 추출하는 함수로 했더니 불러올 수는 있었습니다! 그렇지만 원래 의도한 것인 2번 + 4~10번을 한꺼번에 불러올 수는 없었는데요, 이를 간단한 리스트를 통해 확인해보니
> 
> ```python
> a = [1,2,3,4,5]
> a[3:4],a[1]
> ```
> 
> 다음과 같이 코딩했을때 결과가 ([4], 2)가 나왔습니다. 그런데 여기에서 4의 경우 리스트이고 2는 정수형에 해당하는데, 이렇게 나온 이유는 리스트를 slicing했을때의 결과는 리스트로 나오고, 인덱싱했을때는 문자열로 나오기때문에 이때 위에서 의도한대로 'room_type', neighborhood : minstay라는 항목은 리스트와 문자열을 더하는거라 계산이 안된다는 것을 확인했습니다.
> 
> 따라서 원래 의도대로 만들기위해 아예 자료형을 모두 리스트로 바꾼다음 이를 대입하는 방법으로 사용하여
> 
> ```python
> column_extract = [2] + list(range(4,11))
> airbnb_remake = airbnb_db.iloc[:, column_extract]
> ```
> 
> 와 같이 만들어서 해결했습니다

추가로 이렇게 만들어보니 loc하고 iloc함수가 각각 location, integer_location의 줄임말인것을 확인할 수 있네요

**Comment by yoomambo** [comment]
@lsj0822 오... 성준멘티님 혼자 구글링 잘하셨네요! 굿굿
