### ISSUE TITLE
[GitHub] pull request 버튼이 보이지 않음

### ISSUE THREAD

**Issue by jiwoo4424** [4Moyede/HexatonClass-01#109]
# 문제 

이번 주 과제를 push하고 pull request를 하려고 하니 pull request가 활성화 되어 있지 않음

# 원인

closed되지 않은 pull request가 존재하여 일어난 문제인 거 같음 
![image](https://user-images.githubusercontent.com/76776979/104501065-94c8da80-5622-11eb-9044-8438c60749d7.png)

# 시도 
1.기존의 pull request를 closed하고 다시 push (S_JW의 브랜치 속 파일들은 추가가 되어있고 수정이 다 되어있음)
2. Everything up-to-date라고 뜸..
3. git checkout main 명령어를 통해 파일들을 수정하는 건가 싶어서 도전해보고 싶었지만 혹시나 잘못했다가 엉망진창으로 만들까봐 issue란에 올림
4. git log 와 git reflog를 통해 원하는 commit으로 다시 돌아갈 수 있고 거기서 reset이나 rebase를 통해 수정할 수 있다고 하는데 잘못 건드려서 망칠까봐 무서워서 질문합니다ㅜㅜㅜㅜ  

# 질문
위의 사진에서 내가 실행되었으면 하는 commit은 맨 밑의 [S_Add] Day 03 Homework와 그 위의 [S_Ref] modified~~ 이다.
이를 위해서는 어떻게 해야할까요 ...?

**Comment by 4Moyede** [comment]
안녕하세요 강형구 멘토입니다.

ㅎㅎ GitHub를 대하는 그런 조심스러운 자세 아주 좋습니다
1. 음 일단 이번에 pull request 잘 보내신거 같은데 pull request가 활성화 되어있지 않다는 건 문제가 해결된걸까요? 아니면 다른 것을 질문하신걸까요?
2. 그리고 저번 과제에 피드백 사안이 있어서 저번 pull request를 받지 않았습니다.  
그래서 아직 remote의 main branch에는 저번 과제부터 없으므로 이번에 pull request를 보내실 때 저번 commit도 다 뜨는 것 같습니다.

**Comment by jiwoo4424** [comment]
> 안녕하세요 강형구 멘토입니다.
> 
> ㅎㅎ GitHub를 대하는 그런 조심스러운 자세 아주 좋습니다
> 
> 1. 음 일단 이번에 pull request 잘 보내신거 같은데 pull request가 활성화 되어있지 않다는 문제는 해결되신걸까요? 아니면 제가 질문을 잘못 이해하고 있는걸까요?ㅠㅠ
> 2. 그리고 저번 과제에 피드백 사안이 있어서 저번 pull request를 받지 않았습니다.
>    그래서 아직 remote의 main branch에는 저번 과제부터 없으므로 이번에 pull request를 보내실 때 저번 commit도 다 뜨는 것 같습니다.

궁금했던 부분이 해결이 되었습니다! pull request 버튼이 활성화가 안된 것은 제 노트북의 문제인 거 같아요 !! 감사합니다~
