### ISSUE TITLE
[Environment] Matplotlib모듈을 설치했음에도 인식하지 못하는 오류

### ISSUE THREAD

**Issue by JaebeomHan** [4Moyede/HexatonClass-01#113]
**Content** : Matplotlib 사용 중에 발생한 오류입니다.

## 사진 첨부
![image](https://user-images.githubusercontent.com/76792181/104573668-80bfc000-5698-11eb-9611-9fbc124cb816.png)
<br>
## 설명
Pandas 사용시에도 같은 문제가 발생하여 
![image](https://user-images.githubusercontent.com/76792181/104575062-190a7480-569a-11eb-8526-a7b5bc099c2e.png)
이 글을 참고하여 해결하였으나,,
Matplotlib은 찾아봐도 마땅한 방법이 없네요.

**Comment by yoomambo** [comment]
@JaebeomHan matplotlib를 아나콘다 가상환경에 깔았나요?

**Comment by JaebeomHan** [comment]
> @JaebeomHan matplotlib를 아나콘다 가상환경에 깔았나요?

관련 글도 찾아서 설명대로 진행했지만 해결되지 않아 초기 상태부터 다시 진행해보려 합니다.

**Comment by yoomambo** [comment]
> > @JaebeomHan matplotlib를 아나콘다 가상환경에 깔았나요?
> 
> 관련 글도 찾아서 설명대로 진행했지만 해결되지 않아 초기 상태부터 다시 진행해보려 합니다.

무작정 지우지말고, 패키지를 가상환경에 설치했는지, base에 설치했는지를 먼저 파악해보세요

`conda list` 명령어 치면 패키지가 설치됬는지 나올겁니다

**Comment by JaebeomHan** [comment]
> > > @JaebeomHan matplotlib를 아나콘다 가상환경에 깔았나요?
> > 
> > 
> > 관련 글도 찾아서 설명대로 진행했지만 해결되지 않아 초기 상태부터 다시 진행해보려 합니다.
> 
> 무작정 지우지말고, 패키지를 가상환경에 설치했는지, base에 설치했는지를 먼저 파악해보세요
> 
> `conda list` 명령어 치면 패키지가 설치됬는지 나올겁니다

가상환경 다시 만들었더니 해결됐습니다~~
