### ISSUE TITLE
[Python] import 구문을 하단에 쓰면 안되는 이유

### ISSUE THREAD

**Issue by dlrudgnsdlek** [4Moyede/HexatonClass-01#119]
**Content** : <pre><code>import matplotlib.pyplot as plt</code></pre>
히스토그램을 그리는 문제에서 matplotlib 라이브러리의 pyplot 모듈을 사용했는데요. 이 모듈을 import 하는 구문을 맨 위에 써야하는 이유가 궁금합니다.
****
**Googling keyword** :  python import 위치, python import 맨 위
*****
**Googling 결과** : 
[https://blog.naver.com/wwwkasa/221468801738](url)
[https://eehoeskrap.tistory.com/413](url)
결과적으로 import 구문을 맨 위에 쓰는 이유는 **파이썬에서 권장하는 스타일**이기 때문입니다...
******
**개인적인 생각** : 
왜 파이썬에서는 맨 위에 쓰는것을 권장하는지 생각해봤을 때, 저의 개인적인 생각은 import한 모듈이나 패키지만 보더라도 밑에 어떤 정보가 있을지 한번에 예측이 되기 때문입니다. 이번 과제를 예로 들면
<pre><code>import pandas as pd
import numpy as np
import matplotlib.pyplot as plt</code></pre> 
 을 통하여 테이블형 데이터와 다차원 배열에 관한 데이터가 있고, 그래프가 있을것이라고 한번에 예측할 수 있는 것 처럼요!
저의 생각은 여기까지인데 다른 멘티님들의 생각도 궁금하네요:)

**Comment by NA-DK** [comment]
import 구문을 맨 위에 쓰지 않아도, 오류는 발생하지 않았던 것 같습니다. 그럼에도 이 구문을 최상단에 써주면 경훈님이 언급해준 부분처럼 모듈과 패키지를 미리 써줌으로써, 어떤 정보가 있는지 알아보기 쉬워지기 때문인 것 같습니다...!

**Comment by 4Moyede** [comment]
안녕하세요 강형구 멘토입니다.
아주 좋은 질문 올려주신거 같아서 기분이 좋습니다.

경훈 멘티님과 덕규 멘티님의 의견은 제가 생각해도 매우 맞는 이유라고 생각합니다.
import가 위에 다 있어야 내가 이 파일을 실행면 어떤 일이 일어나고 제대로 실행하려면 어떤 패키지를 설치해야 하는지 알 수 있는 것이 협업에도 매우 좋은 코드라고 생각합니다.

추가적으로 제 생각을 추가하자면,
python은 interpreter 언어라서 맨 위에 두지 않아도 오류가 뜨지않는 것이고, 다른 언어는 import를 하는 부분과 main 코드가 실행 되는 부분이 정확하게 나누어져 있어서 항상 맨위에 해야합니다.
<img width="540" alt="image" src="https://user-images.githubusercontent.com/38308646/104815612-f8d4e400-5858-11eb-89e3-dd9005b605a3.png">
그래서 기존의 C에서 부터 시작되었던 관습으로써도 이어져 오는 것이 아닐까 라는 생각도 합니다. 

여기서 interpreter 언어란, 처음부터 끝까지 문제가 없는지 확인하고(컴파일이라고 합니다) 코드를 실행 파일로 바꿔서 실행 파일을 실행하는 형식이 아니라, 일단 코드 자체가 실행이 가능하여 코드 첫 줄부터 실행하고 진행하여 보다가 문제를 만나면 그때 오류를 발생시키는 언어입니다.
참고 : https://ithub.tistory.com/86

**Comment by dlrudgnsdlek** [comment]
감사합니다!
