### ISSUE TITLE
[Python] for 구문에 i를 쓰면 안되는 경우

### ISSUE THREAD

**Issue by NA-DK** [4Moyede/HexatonClass-01#120]
**Content** :
import numpy as np

airb_new = airb.drop_duplicates(['accommodates'],keep='first')
airb_new_sorted_by_values = airb_new.sort_values(by='accommodates',ascending=True)

accommodate_list=list(np.array(airb_new_sorted_by_values['accommodates'].tolist()))

**for i in accommodate_list: 
    print("This is accommodates's value :",i)**

_이 부분에서 마지막에 i를 쓰지 않는 것이 좋다고 하였는데, 왜 그런지 궁금합니다..!_

Googling : for in in list, python i , python for

흠 사실 정상적으로 출력이 되어서 문제가 될 꺼라고 생각은 안했는데,  구글링을 해봐도 해결책을 찾지 못했습니다..
이유를 아시는 분이 있을까요?!

**Comment by 4Moyede** [comment]
안녕하세요 강형구 멘토입니다.

for 문에서 i 를 사용하는 것은 구글 검색을 해보시면 아시겠지만 굉장히 자주 있는 일이고 많이 쓰여온 방식입니다. 따라서 그 방식이 틀렸다고는 할 수 없지만 python 이라서 사용할 수 있는 코드니까 조금 더 의미 있는 변수를 사용하는 것이 어떨까 하는 피드백 이었습니다. 

C++과 Python의 코드를 비교하면서 설명해보겠습니다.

<img width="408" alt="image" src="https://user-images.githubusercontent.com/38308646/104816157-89f98a00-585c-11eb-9320-134f3dd12805.png">

python에서는 위와 같이 "for 변수 in 묶음"에서 묶음 부분에 list가 바로 올 수 있습니다.

<img width="419" alt="image" src="https://user-images.githubusercontent.com/38308646/104816018-b5c84000-585b-11eb-8abb-c7ee5998eb94.png">

C/C++, java에서는 for 문 내에서 묶음이 바로 사용되는 것이 아니라 iterator를 사용할 수 밖에 없습니다. 따라서 이 언어들에서는 for문에서 사용되는 변수 이름을 index의 i로 사용하는 것이 국룰이었습니다.
하지만, python에서는 직접적으로 리스트 내의 값들을 받을 수 있으니 i가 아닌 다른 이름으로 변수 이름을 짓는 것이 더 맞지 않는가 라고 생각합니다.

**Comment by yoomambo** [comment]
@NA-DK for문에서 iteration 되어서 나오는 변수들을 i 에서 좀 더 의미있는 변수로 바꾸면 아마 협업자들과 일할 때 분명 도움될 것입니다. 확인하셨을까요?
