### ISSUE TITLE
[Python] 최적의 변수명짓기

### ISSUE THREAD

**Issue by lsj0822** [4Moyede/HexatonClass-01#121]
**Commit** : commit 번호
**Content** : 질문 내용에 대해서 서술하시오

```python
PFilter = int(input("원하는 가격을 입력하시오 : "))
NFilter = input("지역을 입력하시오 : ")
RFilter = int(input("최소 리뷰수를 입력하시오 : "))

airbnb_filter = airbnb_db[(airbnb_db["price"]>PFilter) & (airbnb_db["neighborhood"] == NFilter) & (airbnb_db["reviews"] > RFilter)]

print('Start Filtering Job')
print('The number of house :',len(airbnb_filter.index))
airbnb_filter
```

이번 과제에서 4번문제의 코드입니다. 4번문제 필터링의 경우 원래는 변수를 굳이 사용할 필요없이 250, Downtown, 5를 각각 대입하여 구해도 상관없지만, 그래도 필터?라는 역할을 수행한다는 것을 보여주고 싶어 필터에 필요한 3가지 변수를 각각 PFilter, NFilter, RFilter로 정했습니다.

이렇게 정한 이유는 처음에는 말그대로 PriceFilter, NeighborhoodFilter, ReviewsFilter로 정하려했지만, 이것이 

```python
airbnb_filter = airbnb_db[(airbnb_db["price"]>PFilter) & (airbnb_db["neighborhood"] == NFilter) & (airbnb_db["reviews"] > RFilter)]
```

저는 필터를 다음과 같이 적었기에 이 구문에 이 변수 3개가 그대로 들어간다면, 내용이 너무 길어 화면에 짤려보였습니다.

그렇기에 정한 필터이름이 Price, Neighborhood, Reviews의 앞글자를 딴, PFilter, NFilter, RFilter로 정하고, 이렇게 코딩하여 초안으로 제출했습니다.

그러나 이것은 어디까지나 제가 약속한 내용일뿐, 멘토님이나 다른 멘티님들이 보시기엔, 이 변수가 어떤 변수를 의미하는지 주석으로 달아주지않는이상 직관적인 이해가 힘들겠다는 생각이 들었습니다

따라서 가장 좋은 방법은 다른 멘티님들이 이번 과제에서 제출한것처럼 price_filter, review_filter와 같이 변수를 쉽게 파악할 수 있게 모든 정보를 드러내는 방법이지만, 이렇게 하면 이 변수를 반복해서 사용할때 경제적이지 못하다는 단점이 있습니다.

그래서 몇가지 대안을 생각해봤는데

-  변수명에 필요한 정보를 모두 살리기(review_filter)
-  띄어쓰기를 기준으로 2-3글자만 살리기 (rev_fil)
-  중요한 정보만 모두 적고, 별로 중요하지 않은 정보는 변수에서 2-3글자만 살리기 (review_fil)

이중에서 가장 경제적인 코드는 2번째 방법으로 변수의 이름을 짓는것이지만, 그래도 최소한의 정보는 파악할 필요가 있기 때문에 (즉, rev_fil같은 경우 rev가 reviews인지 아니면 회전수를 말하는 revolution인지... 정확히 파악하기 힘듦) 3번째 방법으로 변수의 이름을 정의하는 것이 가장 좋은 방법이라 생각합니다!

**Comment by JaebeomHan** [comment]
저는 1번째 방법을 더 선호하는데요, 코드가 길어진다면

```
airbnb_filter = airbnb_db[ (airbnb_db["price"] > PFilter)
                         & (airbnb_db["neighborhood"] == NFilter)
                         & (airbnb_db["reviews"] > RFilter) ]
```
이런식으로 줄바꿈을 해보는 것도 괜찮다고 생각합니다.

오히려 가독성도 올라가는 듯 싶네요

**Comment by 4Moyede** [comment]
@JaebeomHan 줄바꿈해서 하는 방식은 자주 쓰이고 있는 방식입니다!
