### ISSUE TITLE
[Environment] 쥬피터파일 열어보면 image가 안보이는데, 어떤 이유일까요?

### ISSUE THREAD

**Issue by jiwoo4424** [4Moyede/HexatonClass-01#137]
**Content** : 쥬피터파일 열어보면 image가 안보이는 문제 (밑의 사진 참고)
![image](https://user-images.githubusercontent.com/76776979/104990738-91898080-5a60-11eb-8769-c874cec15db5.png)

이는 내 브랜치 속의 디렉토리에 해당 images들이 없어서 안보이는 것 !
내가 컴퓨터로 주피터노트북을 사용하는 환경 속 디렉토리 안에는 image폴더를 넣어놔서 직접 코드를 짜는 동안은 사진들이 보였지만 원격저장소 안에는 해당 폴더가 없기 때문에 이미지가 보이지 않는다는 거,,,,,

**Comment by 4Moyede** [comment]
안녕하세요 강형구 멘토입니다.
local에서 Jupyter notebook 작성하실 때에 복사 붙여넣기로 이미지를 추가하신 것 같은데 이 사진 파일은 어디서 저장되는 걸까요?

**Comment by jiwoo4424** [comment]
(https://user-images.githubusercontent.com/76776979/104990738-91898080-5a60-11eb-8769-c874cec15db5.png)
이렇게 링크가 적혀있는 걸로 보아서 github 서버에 자동 저장이 되는 것이 아닐까용...?

**Comment by yoomambo** [comment]
> **Content** : 쥬피터파일 열어보면 image가 안보이는 문제 (밑의 사진 참고)
> ![image](https://user-images.githubusercontent.com/76776979/104990738-91898080-5a60-11eb-8769-c874cec15db5.png)
> 
> 이는 내 브랜치 속의 디렉토리에 해당 images들이 없어서 안보이는 것 !
> 내가 컴퓨터로 주피터노트북을 사용하는 환경 속 디렉토리 안에는 image폴더를 넣어놔서 직접 코드를 짜는 동안은 사진들이 보였지만 원격저장소 안에는 해당 폴더가 없기 때문에 이미지가 보이지 않는다는 거,,,,,

지우멘티님이 잘 말씀하신 것 같습니다. 원격저장소에 해당 파일과 폴더가 없기 때문에 그런일이 발생을 하는 것이지요. 그럼 추후에는 어떻게해야 주피터파일에서 이미지 파일이 보일까요?

**Comment by jiwoo4424** [comment]
> (https://user-images.githubusercontent.com/76776979/104990738-91898080-5a60-11eb-8769-c874cec15db5.png)
> 이렇게 링크가 적혀있는 걸로 보아서 github 서버에 자동 저장이 되는 것이 아닐까용...?

@4Moyede

**Comment by 4Moyede** [comment]
ㅎㅎ일단 제가 질문을 잘못 이해한 점 있는 것 같습니다.
Drag & Drop 이 아닌, 직접 경로 설정하셔서 주피터 파일을 작성한 경우, image 파일 역시도 add 해주어야 하는 것 맞습니다! 정확히 잘 찾아보셨구요:)

제가 올린 질문은 정말 궁금해서 올린 댓글이었습니다.
"Drag & Drop 으로도 주피터 파일 내에 사진을 표현할 수 있는데 그런 경우 어디에 그 사진에 대한 데이터가 저장이 되는 걸까?" 였습니다.

**Comment by jiwoo4424** [comment]
> ㅎㅎ일단 제가 질문을 잘못 이해한 점 있는 것 같습니다.
> Drag & Drop 이 아닌, 직접 경로 설정하셔서 주피터 파일을 작성한 경우, image 파일 역시도 add 해주어야 하는 것 맞습니다! 정확히 잘 찾아보셨구요:)
> 
> 제가 올린 질문은 정말 궁금해서 올린 댓글이었습니다.
> "Drag & Drop 으로도 주피터 파일 내에 사진을 표현할 수 있는데 그런 경우 어디에 그 사진에 대한 데이터가 저장이 되는 걸까?" 였습니다.

열심히 찾아보고 직접 해본 결과 , 주피터 파일 내에서 Drag & Drop이 가능한 경우는  이미지 파일을 컴퓨터상에 저장했을 때만 가능하고 캡쳐 도구를 이용해 캡쳐한 사진을 바로 Drag & Drop(컴퓨터 내 저장x)을 하려 하니 안되서 복사, 붙여넣기를 해보려 했지만 그것도 안되는 걸 보니 결론은 잘모르겠다입니다 ! ㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎ
