### ISSUE TITLE
[Python] for i in range 문

### ISSUE THREAD

**Issue by jiwoo4424** [4Moyede/HexatonClass-01#138]
**Content** : 아래 사진에서 for i in range 부분에서 i를 쓰면 안되는 이유
![image](https://user-images.githubusercontent.com/76776979/104992408-56894c00-5a64-11eb-8021-8935d26e1bc0.png)

```python
for i in range(len()) :  #파이썬에서 권장하지 않는 코드
```

Python에서 iterable한 자료구조(예를 들면 list, set, dictionaryemd)를 for문을 통해 순회할 때 주로 range와 enumerate 두 가지를 사용하는데 구글링을 해보았을 때 위 같은 코드를 파이썬에서 권장하지 않는다고 나와있었습니다 . 

이에 대한 이유로 

1. range는 len함수와 같이 사용해야한다. 
2. 리스트와 같은 자료구조의 인덱스에 접근해야 한다. 

제가 쓴 코드가 파이토닉하지못함을 멘토님께서 지적해주신게 아닐까 ,,,,? 생각이 듭니다 

이런 이유가 아니라면 정확히 왜 쓰면 안되는 지는 잘 모르겠습니다. (결과를 출력했을 때 에러도 없고 원하는 결과가 나오기 때문에 )

**Comment by 4Moyede** [comment]
안녕하세요, 강형구 멘토입니다.
덕규 멘티님이 같은 질문을 해주셨었습니다. #120

**Comment by jiwoo4424** [comment]
> 안녕하세요, 강형구 멘토입니다.
> 덕규 멘티님이 같은 질문을 해주셨었습니다. #120

앗 네 ! 확인했습니다. 제가 찾아본 이유랑 같은 거 같습니다 !!!

**Comment by yoomambo** [comment]
@jiwoo4424 지우멘티님께서 확인하셨으므로 closed 하겠습니다
