### ISSUE TITLE
[Python] 문자열 입력시 '',"" 사용

### ISSUE THREAD

**Issue by jiwoo4424** [4Moyede/HexatonClass-01#139]
**Content** :  아래의 코드를 더 간결하게 쓰는 법
```python
print("This is accommodates'" + "s value : "
```
 파이썬에서 문자를 입력할 때  작은 따옴표('')와 큰 따옴표("")를 둘 다 사용해도 되고 ""안에 ''를 쓰는 것도 가능합니다 . 이 부분을 몰랐던 게 아니고 문제의 발단은 아래와 같습니다....

1. 주피터 노트북 상에서 '나 "를 입력하면 자동으로 '가 2개 또는 "가 2개가 입력됩니다 ! 
2. 생성된 두개의 "" 중 하나만 지우고 싶으면 뒤의 "부분을 지워야 하나만 지워지고, 앞의 "를 지우게 되면 ""가 다 사라져버리는 일이 발생 

**결론**

 이 간단한 규칙을 모르고 혼자 이상하게 하다가 화가 나버려서 위의 파이썬 코드처럼 분리해서 적게 됨 이후에 이 규칙을 발견하게 되고 뒤의 코드들에서는 제대로 작성하였습니다... 하핫 이 분을 놓치지 않고 지적해주셔서 민망합니다 ㅎㅎㅎㅎㅎㅎㅎ

**Comment by yoomambo** [comment]
@jiwoo4424 민망민망 ㅎㅎㅎㅎ 그래도 잘 바꿔봐서 다행이네요~

**Comment by jiwoo4424** [comment]
> @jiwoo4424 민망민망 ㅎㅎㅎㅎ 그래도 잘 바꿔봐서 다행이네요~

헤헷 ㅎㅎ 제가 확인했으니 issue 제가 닫으면 되는 거죠 ?????
