### ISSUE TITLE
[Python] 가독성 좋은 코드짜기 

### ISSUE THREAD

**Issue by jiwoo4424** [4Moyede/HexatonClass-01#140]
**Content** : 아래와 같이 코드를 짜면 안좋은 점
```python
no_overlap_accommodates = no_overlap['accommodates']
no_overlap_accommodates = no_overlap_accommodates.sort_values()
```

```python
no_overlap_accommodates = no_overlap['accommodates'].sort_values()
```
맨 위의 코드처럼 똑같은 변수를 계속 바꾸면 가독성이 떨어지고 나중에 코드를 짤 때 헷갈려서 멘토님께서 위 처럼 코드를 짜면 안좋다고 언급해주신 거 같은데 아래와 같이 코드를 수정할 수 있습니다 !!

다른 이유가 존재하면 같이 의견을 나누고 공유해봅시다 !

**Comment by jiwoo4424** [comment]
같은 맥락인 거 같아서 따로 이슈를 만들지 않고 여기에 추가해서 쓰겠습니다. 

```python
print("We select only Good information about airbnb dataset : ")
print("1  :  room_type")
print("2  :  neighborhood")
print("3  :  reviews")
print("4  :  overall_satisfaction")
print("5  :  accommodates")
print("6  :  bedrooms")
print("7  :  price")
print("8  :  minstay")
```
위와 같이 코드를 짜면 누가 봐도 좋은 코드라는 생각이 들지는 않을 것입니다 . 이 부분을 해결하기 위해서 멘토님이 올려주신 솔루션을 참고했고 거기서 enumerate함수라는 것을 알게 되어 공유하고자 합니다. 

다른 이슈에서 제가 for i in range(len())이라는 코드가 좋지 않다고 말했는데 이는 python에서는 직접적으로 리스트 내의 값들을 받을 수 있어서 입니다. 따라서 for i in range(len())의 코드 대신 보통 아래와 같은 enumerate을 많이 사용합니다.
```python
for i, v in enumerate(t):
   print("index : {}, value: {}".format(i,v))
```

인덱스 번호와 컬렉션의 원소를 tuple형태로 반환해주고, 반복문 사용 시 몇 번째 반복문인지 확인이 필요할 때 사용 가능합니다. 
(출처: https://wikidocs.net/16034)

따라서 이를 이용해서 코드를 짜주면 
```python
for idx, column in enumerate(columns_list):
    print(idx+1, " : ", column)
```
8줄의 코드를  반복문을 사용해 단 2줄로 바꿀 수 있습니다 !

**Comment by JaebeomHan** [comment]
파이썬에는 긴 코드를 편리하게 줄일 수 있는 방법이 참 많은 것 같습니다. enumerate 함수 같은 경우에도 그 중 하나고요. 매 순간 효율적인 코드만을 짤 수는 없겠지만 항상 여러가지 가능성을 열어두고 확인해봐야겠습니다.

**Comment by yoomambo** [comment]
@jiwoo4424 크.. 제가 원하는 부분을 바로 찾으셨네요. 좋습니다~~

@JaebeomHan 재범 멘티님도 잘 확인하셨으니 다른 코드에 꼭 적용해보시길 바랍니다.
