### ISSUE TITLE
[Python] 함수안에 global 변수를 쓰면 안되는 이유

### ISSUE THREAD

**Issue by yoomambo** [4Moyede/HexatonClass-01#141]
**Content** : 

```python
def make_dict(column):
    result_column_name = set(airbnb_data_select[column])
    return result_column_name

result_dict = {'room_type': make_dict('room_type'),
               'neighborhood': make_dict('neighborhood'),
               'reviews': make_dict('reviews')}
```

@JaebeomHan 멘티님

멘티님 코드보면, make_dict 함수에서 airbnb_data_select는 global 변수를 넣은 것 같은데, 이렇게 짜면 함수의 의미가 없어집니다.

왜일까요?~?

다른 멘티분들도 한 번 고민해보시길 바랍니다.

**Comment by JaebeomHan** [comment]
앞어 정의해둔 airbnb_data_select의 데이터가 변했을 때 함수 전체의 결과가 바뀌기 때문인가요?

**Comment by jiwoo4424** [comment]
> **Content** :
> 
> ```python
> def make_dict(column):
>     result_column_name = set(airbnb_data_select[column])
>     return result_column_name
> 
> result_dict = {'room_type': make_dict('room_type'),
>                'neighborhood': make_dict('neighborhood'),
>                'reviews': make_dict('reviews')}
> ```
> 
> @JaebeomHan 멘티님
> 
> 멘티님 코드보면, make_dict 함수에서 airbnb_data_select는 global 변수를 넣은 것 같은데, 이렇게 짜면 함수의 의미가 없어집니다.
> 
> 왜일까요?~?
> 
> 다른 멘티분들도 한 번 고민해보시길 바랍니다.

result_column_name라는 지역 변수에 set(airbnb_data_select[column])라는 전역 변수를 대입하는 거라 airbnb_data_select라는 전역 변수 자체가 변하지않아서 안틀린 거 같은데 ,,,, 혹시 이유가 무엇인지 말해주실 수 있나요 ??? 지금 궁금해서 1시간동안 구글링했는데 모르겠어요

**Comment by JaebeomHan** [comment]
![function_issue](https://user-images.githubusercontent.com/76792181/105202703-9c8a0100-5b85-11eb-9956-27498c1983a2.png)

제가 수정해본 코드입니다.

함수 안에 지역변수만 들어가게끔 해봤습니다.

지역변수만을 사용한 함수를 원하시는 멘토님의 생각은 이해가 갑니다만

수정하기 전의 전역변수를 사용한 코드가 잘못되었다는 말씀은 정확하게 이해하지 못했습니다.

**Comment by yoomambo** [comment]
```python
# pandas_function.py

def make_dict(column):
    result_column_name = set(airbnb_data_select[column])
    return result_column_name
```

```
# main.py

import pandas_function

airbnb_data_select = [] # 이 부분은 전에 airbnb_data_select라는 DataFrame이라고 가정을 해봅시다.

result_dict = {'room_type': pandas_function.make_dict('room_type'),
               'neighborhood': pandas_function.make_dict('neighborhood'),
               'reviews': pandas_function.make_dict('reviews')}
```

1. pandas_function 이라는 파이썬 파일에 make_dict라는 함수를 정의할게요
2. main.py에서 pandas_function 모듈을 import해서 result_dict라는 변수에서 make_dict를 불러와서 사용해보겠습니다.
3. 위의 코드는 실행되지 않습니다.

@jiwoo4424 @JaebeomHan @dlrudgnsdlek @NA-DK @lsj0822 
좋은 질문과 이슈라서 모든 멘티분들께 질문합니다. (수업 전까지 한명씩 답하시길 바랍니다.)

1. 제가 이 코드를 보여준 이유를 생각해보시길 바랍니다. 왜 이 코드를 보여주며 예시를 들었을까?
2. 재범이가 main code에서 함수를 정의하고 썼을 때는 돌아갔는데, 지금은 왜 안돌아갈까?
3. 그럼 위의 코드를 어떻게 수정해야할까? 나라면?

이 3가지 질문에 답하고, 예시 코드를 들어서 적어주시길 바랍니당

아마 여러분들이 스스로 답하게 된다면 파이썬 실력은 한층 더 올라갈 것입니다!

**Comment by 4Moyede** [comment]
안녕하세요 강형구 멘토입니다.
혁준 멘토님과 제가 회의중에 이 코드에 대해서 피드백 해야겠다고 결정한 이유에 대해서는 혁준 멘토님이 잘 정리해 주셨으니 잘 생각해보시면 됩니다.

음 추가적으로 전역변수와 지역변수의 차이점에 대해서 말하자면, 이건 좀 매우 컴퓨터공학적인 이야기이지만, 궁금하시다니 제가 아는 한으로 알려는 드리겠습니다. 이해가 안되셔도ㅋㅋ 하나만 기억하시면 됩니다.

> 전역변수는 왠만하면 사용을 지양하자!

자 그럼 이제 두 변수의 차이에 대해서 설명하자면, **저장되는 장소가 다릅니다.**
전역변수는 Static에 지역변수는 Stack에 저장이 됩니다. Static에 저장되는 변수는 한번 할당되면 프로그램이 끝날 때까지 그 메모리를 유지하고, Stack에 저장되는 변수는 할당되었다가 사라지고 합니다.

그렇다면, '왜 전역변수를 지양해야 하는가'애 대해서는, 우리는 지금 매우 짧게 돌아가는 프로그램을 짜고 있지만, *만약에 서버에 올라가는 프로그램으로 24시간동안 돌아가는 프로그램이라면?*
굳이 Static에 까지 올려야 할 만큼 중요한 변수인가 생각해보아야 합니다. 그리고 보통은 하나의 기능에 필요한 변수는 그 기능이 완료가 되면 보통 필요성이 떨어지며, 다른 서비스를 원활하게 사용하기 위해서는 Stack에 올리는게 더 낫다고 생각합니다. 

짜보시면 알겠지만, 전역 변수로 짜는 코드와 지역 변수로 짜는 코드는 조금 다릅니다. 그러므로, 지금은 비록 짧게 돌아가는 프로그램이지만 전역 변수 사용을 지양하고 지역 변수를 사용하는 방법을 연습해야한다고 생각합니다.
