### ISSUE TITLE
[Python] image file upload 안됨, 변수선언 순서, pandas의 len 이용하기

### ISSUE THREAD

**Issue by yoomambo** [4Moyede/HexatonClass-01#142]
**Content** : 

![image](https://user-images.githubusercontent.com/54018187/105059984-38026f80-5abb-11eb-9126-ce40235e0f54.png)

@JaebeomHan 멘티님

현재 image 파일을 보면 3 가지 문제가 있습니다.

## 1. image file이 안보임

#137 issue를 확인하시고 수정 부탁드리겠습니다.

## 2. filtered_airbnb

위의 변수를 보면 filtered_airbnb 변수 선언은 아래 코드에 되어있어 변수 선언의 순서가 틀렸습니다. 그런데 왜 쥬피터 파일에서는 돌아갈까요? 이유를 답변하시길 바랍니다.

## 3. len(list(filtered_airbnb))

위의 함수에서 좀 더 간결하게 바꿀 수 있습니다. 혹시 어떻게 바꿀 수 있을까요? 아래에 답변하시길 바랍니다.

@lsj0822 @NA-DK @dlrudgnsdlek @jiwoo4424 다른 멘티분들도 댓글 달아보시길 바랍니다.

**Comment by JaebeomHan** [comment]
1. 수정했습니다
2. 제가 코드를 여러번 수정하는 과정에서 filtered_data 변수에 이미 값이 대입된 상태였기 때문에 순서를 바꿔서 써도 그대로 출력된거라고 생각합니다.
3. list()를 굳이 쓸 필요가 없습니다.
