### ISSUE TITLE
[Python] Python File의 오류

### ISSUE THREAD

**Issue by yoomambo** [4Moyede/HexatonClass-01#143]
**Content** : 질문 내용에 대해서 서술하시오

https://github.com/4Moyede/HexatonClass-01/blob/S_JB/Mentee/HJB/02/HW_Calculator.py

파일을 보시면 지금 코드가 바로 안보이는데 왜 이렇게 보일까요? 답글로 한 번 의견을 내주시길 바랍니다.

@JaebeomHan 멘티님 혹시 코드 변환할 때 어떻게 하셨을까요?

**Comment by JaebeomHan** [comment]
음... 질문을 잘 이해하지 못하겠어요. 코드 변환이 뭘 의미하는건지 잘 모르겠습니다.

**Comment by 4Moyede** [comment]
음 그럼 질문을 조금 바꿔서
Calculator 코드 작성을 어디서 하시고 어떻게 제출하셨나요?

**Comment by JaebeomHan** [comment]
> 음 그럼 질문을 조금 바꿔서
> Calculator 코드 작성을 어디서 하시고 어떻게 제출하셨나요?

VScode에서 작성하고 vscode 터미널에서 명령어 쳐서 제출했습니다

**Comment by 4Moyede** [comment]
음 근데 왜 파일 내부가 생긴게 주피터 노트북과 유사할까요?

**Comment by yoomambo** [comment]
> 음 근데 왜 파일 내부가 생긴게 주피터 노트북과 유사할까요?

@JaebeomHan 첨언하자면, 재범 멘티님이 직접 vscode에서 작성하신 파일을 vscode상에서 캡처해보시고,
저 링크타고 들어가서 보여지는 코드와 어떻게 다른지? 그리고 왜 다를지? 를 비교해보시고 원인을 찾아보세요

**Comment by JaebeomHan** [comment]
제가 vscode에서 작성했는데 ipynb 파일로 제출하는줄 알고 주피터로 옮긴 다음에 확장자 ipynb로 바꾸고 제출했다가 py 파일로 제출하는거 뒤늦게 보고 확장자만 py로 바꾸고 올려서 그런 것 같네요.. 확인했습니다.
