### ISSUE TITLE
[Python] str & input 의 결과물 차이점

### ISSUE THREAD

**Issue by yoomambo** [4Moyede/HexatonClass-01#144]
**Content** : 질문 내용에 대해서 서술하시오

```python
switch = str(input(\"계속하시려면 아무 키나, 끝내시려면 N를 입력하세요. \"))
```

@JaebeomHan 재범 멘티님, 혹시 input 받은 content를 str으로 다시 받은 이유가 있을까요?

**Comment by JaebeomHan** [comment]
제 실수입니다...!!
input으로 숫자를 입력받고 싶을 때는 앞에 int를 붙이잖아요 그래서 전에 다른 과제 할 때 예뻐보이게 명시적으로 str, int를 붙여주곤 했는데 이번 과제에서도 저도모르게 str라고 붙여줬네요.
