### ISSUE TITLE
[Python] 함수 이름 지을 때의 문제점

### ISSUE THREAD

**Issue by yoomambo** [4Moyede/HexatonClass-01#146]
**Content** : 

```python
def information():
    good_info = df.loc[:,['room_type','neighborhood','reviews','overall_satisfaction','accommodates','bedrooms','price','minstay']]
    print("We select only Good information about airbnb dataset : ")
    print("1  :  room_type")
    print("2  :  neighborhood")
    print("3  :  reviews")
    print("4  :  overall_satisfaction")
    print("5  :  accommodates")
    print("6  :  bedrooms")
    print("7  :  price")
    print("8  :  minstay")
    return good_info
information()
```

```python
def filtered ():
    filtering = (df.price > 250)&(df.neighborhood == 'Downtown')&(df.reviews > 5)
    df_filtering = df.loc[filtering, :]
    return df_filtering
filtered()
```

```python
def column_value(column):
    my_column_value = {}
    my_column_value[column] = set(df[column].unique())
    return my_column_value

column_value('room_type'), column_value('neighborhood'), column_value('reviews')
```

@dlrudgnsdlek 멘티님의 코드입니다.

@lsj0822 @NA-DK @jiwoo4424 @JaebeomHan 멘티님이라면 함수 이름을 어떻게 바꿀 수 있을까요?

**Comment by lsj0822** [comment]
저같은 경우에는 과제할때 변수하고 함수를 구분하기 위해 변수명은 모든 글자를 소문자로, 함수명은 첫글자를 영어로 지정했어요.

그래서 위의 함수명을 순서대로 Airbnb_Info , Airbnb_Filtering, Airbnb_Covalue로 바꿀 수 있을것같습니다!

**Comment by JaebeomHan** [comment]
> 저같은 경우에는 과제할때 변수하고 함수를 구분하기 위해 변수명은 모든 글자를 소문자로, 함수명은 첫글자를 영어로 지정했어요.
> 
> 그래서 위의 함수명을 순서대로 Airbnb_Info , Airbnb_Filtering, Airbnb_Covalue로 바꿀 수 있을것같습니다!

이 의견에 찬성 한 표 던지겠습니다.

**Comment by jiwoo4424** [comment]
> 저같은 경우에는 과제할때 변수하고 함수를 구분하기 위해 변수명은 모든 글자를 소문자로, 함수명은 첫글자를 영어로 지정했어요.
> 
> 그래서 위의 함수명을 순서대로 Airbnb_Info , Airbnb_Filtering, Airbnb_Covalue로 바꿀 수 있을것같습니다!

저도 보통 함수명을 적을 때 경훈오빠처럼 어떤 구분이 없이 만들기때문에 성준님의 의견 좋은 거 같아요

**Comment by yoomambo** [comment]
### 1. 여러분, 함수는 무조건 동사를 앞으로 하는 것이 제일 좋습니다.

경훈 멘티님처럼 information or column_value 라고 쓰게된다면, 저는 도대체 information이 어떤 정보를 말하는 거지?
column_value가 컬럼에 있는 value를 가지고 오는 건 알겠는데, 어떤 column의 어떤 value를 하겠다는거지? 그리고 column_value를 다루는 걸 알겠는데 get을 하겠다는거지 set을 하겠다는건지, del을 하겠다는건지 저는 의구심이 들 것 같습니다.

가령, set_{}, get_{} 을 많이 쓰고요. 저같은 경우는 make_{}, del_{}, insert_, change_{}, select_{}, init_{} 이런식으로 많이 씁니다.

### 2. 함수이름을 단조롭게 쓰면, 나중에 다른사람 코드와 충돌날 경우가 많습니다.

여러분들이 filtered, information, 이라고 단조롭게 쓴다면 협업할 때, 무조건 충돌이 생깁니다. 

## 위에 두가지 꼭 명심하시고 이건 제발 멘토 말 들으세요.. 저희가 하라고 하는게 아니라 모든 개발자들의 통용된 약속입니다.

그럼...이만....찡긋.... :)

**Comment by yoomambo** [comment]
@dlrudgnsdlek 이건 경훈 멘티님이 확인 댓글 달아주셔야 할 것 같아요. 많은 분들이 댓글을 달아주었기 때문에!

**Comment by dlrudgnsdlek** [comment]
확인했습니다! 멘티님들과 멘토님의 조언 꼭 명심하겠습니다,, 감사합니다!

**Comment by NA-DK** [comment]
뒤늦게 확인했습니다...! 전부 읽어보았습니다 :)
