### ISSUE TITLE
[Python] list 전체를 for 문에 돌리는 방법

### ISSUE THREAD

**Issue by 4Moyede** [4Moyede/HexatonClass-01#147]
**Commit** : 5a405ed7dea101a504dfe97c76de61da2f31611f
**Content** : 
안녕하세요 강형구 멘토입니다.

먼저, @lsj0822 멘티님의 코드입니다.

<img width="586" alt="Screen Shot 2021-01-20 at 1 49 33 AM" src="https://user-images.githubusercontent.com/38308646/105066911-954def00-5ac2-11eb-8d4f-4f9f5c6f6556.png">

부분에서 list 안에 있는 요소들을 모두 꺼내기 위해서는 다음과 같은 방법이 있음을 짚고 넘어가고 싶었습니다.

```python
test_list = [ 1, 2, 3 ]

# python에서 제공해주는 in 을 활용
for element in test_list:
    print(element)

# index를 활용하는 방법
for idx in range(len(test_list)):
    print(test_list[idx])
``` 

여기에서 list는 길이가 언제든 변할 수 있는 자료형이기 때문에, index로 접근해야 할 때에는 range(len(test_list))을 활용하는 것이 더 맞다고 생각합니다.

**Comment by lsj0822** [comment]
아하 제가 리스트를 불러올때 사용한 방법이 두번째인 인덱스를 이용하여 불러오는 방법이었는데, 지금 코드에서는 칼럼이 8개로 확실하니까 range(8)로 썼는데, 정확히는 remake_index라는 리스트 개수가 가변적이니까 나중을 위해서라도 range(len(remake_index))로 리스트가 몇개라도 코드를 수정할 일이 없게끔 만드는게 좋네요!

**Comment by 4Moyede** [comment]
> 아하 제가 리스트를 불러올때 사용한 방법이 두번째인 인덱스를 이용하여 불러오는 방법이었는데, 지금 코드에서는 칼럼이 8개로 확실하니까 range(8)로 썼는데, 정확히는 remake_index라는 리스트 개수가 가변적이니까 나중을 위해서라도 range(len(remake_index))로 리스트가 몇개라도 코드를 수정할 일이 없게끔 만드는게 좋네요!

정확하게 캐치하셨네요!
