### ISSUE TITLE
[Python] set함수와 unique함수

### ISSUE THREAD

**Issue by jiwoo4424** [4Moyede/HexatonClass-01#148]
**Content** :  파이썬에서 리스트를 중복 제거하는 방법

개인적으로 제일 어려웠던 문제였던 4번 문제를 멘토님의 솔루션을 보면서 똑같이 풀어서 내는 것은 나에게 도움이 되지 않을 꺼 같았다. 그래서 여러 방법을 구글링 중 set함수와 비슷한 unique함수를 찾았고 이를 공유하고자 issue를 씀

**set 함수**

1. 순서가 없음
2. 집합 안에서 unique한 값을 가짐
3. mutable 객체

-> set은 dict타입과 동일한 중괄호를 사용하지만 key는 없고 , value만 존재 

**unique함수**

Python 데이터 분석 라이브러리를 사용하는 경우, 사용가능

pandas.unique(value)의 함수 형태를 가지며,  value는 1d-array 형태로 들어가야함( np.array, list , Series 가능)

-> 두 함수의 차이점은 set은 순서가 없고 unique는 순서가 있게 중복을 제거 한다는 것이다 !!

**Comment by lsj0822** [comment]
오 set하고 unique의 차이점을 잘 정리해주신것 같아요!
추가로 과제하면서 알게 된건데, unique의 경우 따로 정렬하는 기능이 없어서 추가로 정렬을 해줘야하지만, set함수의 경우 집합자료형자체가 value를 정렬한 상태로 들어가서 정렬을 안해줘도 된다는 장점이 있었어요

**Comment by JaebeomHan** [comment]
감사합니다 최지우 멘토님 ^^

**Comment by jiwoo4424** [comment]
> 오 set하고 unique의 차이점을 잘 정리해주신것 같아요!
> 추가로 과제하면서 알게 된건데, unique의 경우 따로 정렬하는 기능이 없어서 추가로 정렬을 해줘야하지만, set함수의 경우 집합자료형자체가 value를 정렬한 상태로 들어가서 정렬을 안해줘도 된다는 장점이 있었어요

오오 ! 좋은 팁이네욯ㅎㅎㅎㅎ

**Comment by jiwoo4424** [comment]
> 감사합니다 최지우 멘토님 ^^

같이 열공하자구요 ,,,,,!!! ^^ notion에 글쓰러 가야겠다,,,
