### ISSUE TITLE
[Python] for i in list의 i에 대하여

### ISSUE THREAD

**Issue by NA-DK** [4Moyede/HexatonClass-01#150]
**Content** : 
airb_new = airb.drop_duplicates(['accommodates'],keep='first')
airb_new_sorted_by_values = airb_new.sort_values(by='accommodates',ascending=True)

accommodate_list=list(np.array(airb_new_sorted_by_values['accommodates'].tolist()))

for i in accommodate_list: 
    print("This is accommodates's value :",i)

이 부분에서 저는 accommodate열에서 중복된 값을 지우고, 그 값을 리스트로 변환하여 값들을 i라고 해서
for문을 사용하여 출력했는데... for i in list에서 i를 사용하면 안된다는 이야기를 들었습니다..! 혹시 왜 i를 사용하면 안되는지 
이유를 알고 계신분 있나요?

**Comment by yoomambo** [comment]
#120 혹시 같은 issue 내용같은데.... 이슈를 쓰신 이유가 뭘까...용..?

**Comment by NA-DK** [comment]
앗 확인했습니다... 담번엔 이슈를 좀 더 차분히...ㅠㅠㅠㅠ작성토록 하겠습니다.
