### ISSUE TITLE
[Python] try - except - finally의 Error를 직접 정의할 수 없을까요?

### ISSUE THREAD

**Issue by 4Moyede** [4Moyede/HexatonClass-01#165]
**Commit** : 63612799e7d0984b4b3c3cd5ae0f4b7d2dae4b2c
**Content** : 
try - except - finally 로 Error가 발생했을 때를 위한 샛길을 준비하는 방법을 배웠습니다.

* Python 공식문서, 예외 처리 방법
https://docs.python.org/ko/3/tutorial/errors.html
* Python 내장 예외 종류
https://docs.python.org/ko/3/library/exceptions.html

직접 Error를 정의하는 방법에 대해서 공부하여 직접 발생 시키는 코드를 댓글로 달아봅시다!

**Comment by NA-DK** [comment]
try:
    x = input('세글자만 입력해 주세요.')
    if len(x) !=3:
        raise Exception('세글자를 넘긴 것 같습니다.')
    print(x)
except Exception as err:
    print('오류가 발생했습니다.',err)

흠 이렇게 하는게 맞을까요...?

**Comment by NA-DK** [comment]
`try:
    x = input('세글자만 입력해 주세요.')
    if len(x) !=3:
        raise Exception('세글자를 넘긴 것 같습니다.')
    print(x)
except Exception as err:
    print('오류가 발생했습니다.',err)
`

**Comment by NA-DK** [comment]
```python
try:
    x = input('세글자만 입력해 주세요.')
    if len(x) !=3:
        raise Exception('세글자를 넘긴 것 같습니다.')
    print(x)
except Exception as err:
    print('오류가 발생했습니다.',err)
```

흠 이렇게 짜는게 맞을까요..?!

**Comment by yoomambo** [comment]
> ```python
> 
> try:
> 
>     x = input('세글자만 입력해 주세요.')
> 
>     if len(x) !=3:
> 
>         raise Exception('세글자를 넘긴 것 같습니다.')
> 
>     print(x)
> 
> except Exception as err:
> 
>     print('오류가 발생했습니다.',err)
> 
> ```
> 
> 
> 
> 흠 이렇게 짜는게 맞을까요..?!

올....덕규짜응.... 많이 성장했어

**Comment by dev-LeoKang** [comment]
> ```python
> ```python
> try:
>     x = input('세글자만 입력해 주세요.')
>     if len(x) !=3:
>         raise Exception('세글자를 넘긴 것 같습니다.')
>     print(x)
> except Exception as err:
>     print('오류가 발생했습니다.',err)
> ```
> 
> 
> 흠 이렇게 짜는게 맞을까요..?!
> ```

맞습니다!
Exception 이라는 클래스를 이용한 방법을 잘 찾아서 답해주셨네요!
