### ISSUE TITLE
[Python] if __name__ == "__main__" 란 무엇일까요?

### ISSUE THREAD

**Issue by 4Moyede** [4Moyede/HexatonClass-01#166]
**Commit** : 63612799e7d0984b4b3c3cd5ae0f4b7d2dae4b2c
**Content** : 
```python
if __name__ == "__main__"
    # 여기에 있는 코드는 언제 실행이 되는 걸까요?
```

if문의 안과 밖에 있는 코드의 실행 여부는 어떻게 다를까요?

**Comment by lsj0822** [comment]
과제 보충하면서 조사한 부분을 추가합니다!

간단하게 말하자면, 위의 코드는 이 코드를 직접실행했을때는 실행이 되지만, 다른 모듈에서 import했을때는 실행되지 않습니다.

__name__은 모듈명을 저장하는 변수로, __name__이 선언되어있는 모듈내에서는 __main__이지만, 이를 다른 모듈에서 import했을때는 import한 모듈명으로 저장이 됩니다. 그래서 다른 모듈에서는 __name__이 __main__이 아닌 import한 모듈명이므로 실행이 되지 않습니다

**Comment by dev-LeoKang** [comment]
> 과제 보충하면서 조사한 부분을 추가합니다!
> 
> 간단하게 말하자면, 위의 코드는 이 코드를 직접실행했을때는 실행이 되지만, 다른 모듈에서 import했을때는 실행되지 않습니다.
> 
> __name__은 모듈명을 저장하는 변수로, __name__이 선언되어있는 모듈내에서는 __main__이지만, 이를 다른 모듈에서 import했을때는 import한 모듈명으로 저장이 됩니다. 그래서 다른 모듈에서는 __name__이 __main__이 아닌 import한 모듈명이므로 실행이 되지 않습니다

완벽합니다! 그래서 내가 만든 코드를 모듈로 만들때에는
```python
class MyClass:
    def __init__(self):
        pass

def MyFunction(something):
    print(something)


if __name__ == "__main__":
    myClass = MyClass()
    MyFunction("성준이 짜란다짜란다")
```
와 같이 코드 실행 부분을 묶어 두어야합니다.
