### ISSUE TITLE
[Python] pycache에 대하여

### ISSUE THREAD

**Issue by JaebeomHan** [4Moyede/HexatonClass-01#175]
> ### python 파일을 실행할 때 __pycache__ 파일이 생성되는 경우에 대하여 조사하였습니다.

<br>

## 사전 지식 : 인터프리터 언어
+  인터프리터 언어는 실행 시마다 소스 코드를 한 줄씩 기계어로 번역하는 방식이다.
+  인터프리터 언어의 실행 속도는 컴파일 언어보다 느리다. 하지만 프로그램 수정이 간단하다. 
+  Ruby나 Python과 같은 언어들이 인터프리터 언어에 속한다. (고수준 언어라고 한다.)
+ 인터프리터 언어에서는 머신코드가 아닌 프로그래밍 코드 자체를 사용자의 컴퓨터로 보낸다.
+ 사용자의 컴퓨터에서 코드를 기계어로 바꾸는 과정을 실시간으로 거치게 된다.
+ 사용자의 컴퓨터에서 인터프리터를 보유하고 있어야 한다.

<br>

## 사전 지식 : __pycache__ 폴더
+ python의 소스코드를 실행시키면 인터프리터는 소스코드를 바이트 코드로 변환시킨 후 이를 __pycache__ 폴더에 저장한다.
+ 이는 런타임 과정 중 컴파일 과정을 생략하므로 프로그램 실행 시간을 단축시킨다.
+ .pyc 확장자의 파일(=바이트 코드)이 무조건 생성되는 것은 아니다. 파이썬 파일(.py)이 다른 스크립트에 의해 import 되었을 경우에만 생성된다.

<br>

## 사전 지식 : cpython
+ 일반적으로 python은 C로 구현되어 있다고 알려져 있습니다. 그 구현체를 CPython이라고 합니다. 가장 처음 만들어진 python의 구현체입니다.
+ CPython은우리가 작성하는 파이썬 코드를 바이트코드로 컴파일하고 실행합니다.
+ 다시 말하면 파이썬 코드를 C언어로 바꾸는 것이 아니라 컴파일하여 바이트 코드로 바꾼 후에 인터프리터가 실행됩니다.
+ .py 파일을 실행하면 .pyc 파일이 생성되는데 이것이 CPython이 컴파일한 바이트 코드가 들어있는 파일입니다.
+ 컴파일을 CPython이 했듯이 인터프리트 역시 CPython이 합니다. (인터프리터이면서 동시에 컴파일러인 이유)
+ 이외에도 Jython (java 바이트코드 사용), PyPy (Python자체로 구현) 등이 있지만 설명하진 않겠습니다.

<br>

## 실제 예시 -1
![image](https://user-images.githubusercontent.com/76792181/106310214-8deaca80-62a6-11eb-8dce-da05f2041629.png)
+ 제가 4주차에 제출한 과제입니다.
+ 보시면 __pycache__ 폴더에 Error.cpython-39.pyc 파일이 존재하는 것을 확인할 수 있습니다.
<br>
Error.cpython-39.pyc 같은 경우에는 Error.py 파일에 대한 바이트코드라고 보시면 됩니다. 파이썬의 버전을 식별할 수 있는 텍스트를 포함하여 추가 설명이 이름에 주어집니다. 이는 다른 버전에서 작업한 바이트 코드를 덮어쓰지 않게 하기 위함입니다. 저의 파이썬 버전은 3.9.1이기에 '-39' 라는 버전을 나타내는 텍스트가 뒤에 붙었습니다.

<br>

## 제거 방법
터미널에 다음 문구를 치면 pycache 폴더가 생성되지 않는다고 합니다.

      export PYTHONDONTWRITEBYTECODE=1

**Comment by yoomambo** [comment]
@JaebeomHan 재범 멘티님이 자세하게 적어주어서 제가 더이상 코멘트 안해도 될 것 같네요!

**Comment by dev-LeoKang** [comment]
@JaebeomHan 구글링 엄청 잘하셨네요! 저도 코멘트 없습니다

**Comment by ghost** [comment]
감사합니당,,, 프로젝트를 진행하다보니 캐시 파일이 너무 많이 생겨서 비활성화 해야겠네요.
