### ISSUE TITLE
[Environment] 코딩 환경 바꿀때 가상환경 오류

### ISSUE THREAD

**Issue by lsj0822** [4Moyede/HexatonClass-01#176]
**Content** : 질문 내용에 대해서 서술하시오

코딩 환경을 Jupyter Notebook에서 VSCode로 바꾸려 시도했는데,  가상환경 실행을 똑같이 conda activate <가상환경명>으로 시도해봤지만, 이때 코드가 실행되는 것 처럼 보이지만 가상환경으로 바뀌지 않았습니다.

그래서 이 오류에 대해 구글링을해보니

https://naudhizb.tistory.com/940

이 링크처럼 setting.json 파일에 다음과 같이

```powershell
"terminal.integrated.shell.windows" : "C:\\Windows\\System32\\cmd.exe",
"terminal.integrated.shellArgs.windows" : ["/K", "C:\\anaconda3\\Scripts\\activate.bat C:\\anaconda3"]
```

다음과 같이 추가한 이후에 conda activate <가상환경명>을 했더니 잘 실행이 되었습니다.

그러나 여기에서 생긴 의문점이, terminal.integrated.shellArgs.windows가 무엇인지 궁금해서 이것만 따로 구글링을 해봤지만, 명쾌한 답변을 얻진 못했습니다.

구글링하면서 대충 추측해본것은, shellargs의 역할이 이를 이용하여 cmd를 anaconda prompt로 바꾸는 것이고, 이를 실행시키는 창은 cmd인것 같은데, 맞게 이해한것인가요?? 파워쉘 너무 어려워요...

**Comment by yoomambo** [comment]
음...빨리 답을 해주고 싶은데 저도 처음 보는 부분이라..ㅠㅠ 빨리 댓글을 달기가 쉽지 않네요.
저도 제대로 이해하고 천천히 알려드릴게요!

좋은 질문 고마워요 :)

**Comment by yoomambo** [comment]
```bash
["/K", "C:\\anaconda3\\Scripts\\activate.bat C:\\anaconda3"]
```

이 부분

```bash
["/K", "C:\\anaconda3\\Scripts\\activate.bat", "C:\\anaconda3"]
```
이렇게 변경해야 되지않나요??? 혹시 오타가 있었는지, 아니면 지금 저렇게 세팅했는데 잘되는지 궁금하네요...

**Comment by lsj0822** [comment]
> ```shell
> ["/K", "C:\\anaconda3\\Scripts\\activate.bat C:\\anaconda3"]
> ```
> 
> 이 부분
> 
> ```shell
> ["/K", "C:\\anaconda3\\Scripts\\activate.bat", "C:\\anaconda3"]
> ```
> 
> 이렇게 변경해야 되지않나요??? 혹시 오타가 있었는지, 아니면 지금 저렇게 세팅했는데 잘되는지 궁금하네요...

이렇게 바꿔서 실행해도 잘되고, 원래대로 콤마로 구별하지 않아도 실행은 잘됩니다! 놀랍게도... 이 코드를 아예 빼고 terminal.integrated.shell.windows 만 넣었을때도 잘 실행이 되네요...!

**Comment by lsj0822** [comment]
> > ```shell
> > ["/K", "C:\\anaconda3\\Scripts\\activate.bat C:\\anaconda3"]
> > ```
> > 
> > 
> > 이 부분
> > ```shell
> > ["/K", "C:\\anaconda3\\Scripts\\activate.bat", "C:\\anaconda3"]
> > ```
> > 
> > 
> > 이렇게 변경해야 되지않나요??? 혹시 오타가 있었는지, 아니면 지금 저렇게 세팅했는데 잘되는지 궁금하네요...
> 
> 이렇게 바꿔서 실행해도 잘되고, 원래대로 콤마로 구별하지 않아도 실행은 잘됩니다! 놀랍게도... 이 코드를 아예 빼고 terminal.integrated.shell.windows 만 넣었을때도 잘 실행이 되네요...!

정확한 원인을 찾았는데, 그동안 conda activate로 가상환경을 실행시킬때 cmd환경에서 구동했는데, cmd가 아니라 powershell에서 가상환경을 실행시키려해서 가상환경이 활성화가 되지 않았던것이었습니다.

Terminal에서 Select Default Shell을 클릭하여 cmd로 바꿈으로 해결했습니다

**Comment by yoomambo** [comment]
일단 성준 멘티님의 질문의 퀄리티에 좀 많이 놀랬습니다... 저도 생각도 안해본 부분인데, 저도 여러분들 덕분에 많이 배웁니다...훌쩍

@NA-DK @dlrudgnsdlek @jiwoo4424 @JaebeomHan 다른 멘티분들도 이 부분은 꼭 같이 봤으면 합니다.

자.. 이제 좀 심각한 이야기를 얘기해보죠...!

------

## 1. settings.json

### 1-1. Vscode에서 settings.json 이란?

기본적으로 vscode는 여러 운영체제, 여러 언어들을 기반을 통합해주는 통합개발환경, 그 유명한 Integrated Development Enviroment, IDE 입니다. 그만큼 여러 운영체제, 여러 언어들을 다루다보니 모든 개발환경에 맞추는 IDE를 만들기에는 너무 힘듭니다....(개발자들 죽어가는 소리 바로 옆까지 들려요..)

따라서 마이크로소프트 사는 이러한 문제를  **사용자**에게 바로 책임전가를 합니다. 

>It is easy to configure Visual Studio Code to your liking through its various settings. Nearly every part of VS Code's editor, user interface, and functional behavior has options you can modify.

[Visual Studio Code 공식 Docs](https://code.visualstudio.com/docs/getstarted/settings) 을 들어가면 책임전가를 당당히 말하고 어떻게 세팅할건지 알려줍니다!

_**사용자에게 여러 운영체제, 여러 언어들을 개발할 수 있는 자유를 준 만큼, 그 자유는 개발자들이 감당해야하지요...**_

그 자유를 책임지는, 즉 사용자가 원하는 개발 환경 정보들을 저장하는 파일이 바로 settings.json 파일입니다.
말 그대로 여러분들의 개발환경 **세팅** 을 도와주는 것이지요!

### 1-2. settings.json을 어떻게 써야하나?

기본적인 settings.json은 여러분들이 vscode 깔았을 때, default로 설정되어있을 겁니다.

> Settings file locations#
> By default VS Code shows the Settings editor, but you can still edit the underlying settings.json file by using the Open Settings > (JSON) command or by changing your default settings editor with the workbench.settings.editor setting.

> Depending on your platform, the user settings file is located here:

> - Windows %APPDATA%\Code\User\settings.json
> - macOS $HOME/Library/Application Support/Code/User/settings.json
> - Linux $HOME/.config/Code/User/settings.json
> The workspace settings file is located under the .vscode folder in your root folder.

> Note: In case of a Multi-root Workspace, workspace settings are located inside the workspace configuration file.

위의 링크달아놓은 공식 Docs를 보시면, 이렇게 여러분들의 원래의 settings.json이 어디에있는지 친절히(?) 알려줍니다.
근데 성준멘티님처럼 아나콘다를 추가로 연결하는 작업을 하면서 settings.json을 수정한다면, 아마 성준 멘티님 directory에는
.vscode 라는 폴더가 하나 생겼을겁니다. 원래 settings.json을 가져오되, 성준멘티님이 수정한 부분만 덮어서 쓰겠다는 것이지요.

그럼 여기까지 settings.json이 적어도 어떤 파일이고 왜 이런게 생기는지, 필요한지에 대해서 말씀 드렸습니다.

--------------

## 2. settings.json 안에 요소들 분석

### 2-1. shell.windows

```bash
"terminal.integrated.shell.windows" : "C:\\Windows\\System32\\cmd.exe",
```
이 부분부터 살펴보겠습니다.

Vscode는 위에서 모든 운영체제를 지원한다고 언급하였습니다. 또한 Vscode에서는 terminal을 바로 연결해서 쓸 수 있습니다. 
따라서 terminal.integrate.shell은 vscode에서 보여지는 terminal이고 그 터미널이 windows라는 뜻입니다.

그럼 이 터미널은 뭐랑 연결지을거냐?
아마 우리는 windows 환경에서 쓸 수 있는 터미널은 여러분들은 3가지 일 것입니다.

1. git bash
2. cmd
3. powershell

이 중에서 cmd.exe를 선택한 것입니다.
즉, 성준 멘티님은 vscode에서 터미널을 열었을 때, cmd로 열겠다~ 이런 의미라고 생각하시면 됩니다.

아마 성준멘티님이 "C:\\Windows\\System32\\git-bash.exe" 라고 수정했으면 git bash가 연결될 것입니다.

### 2-2. terminal.integrated.shellArgs.windows

위에서는 vscode에서 기본 터미널을 cmd로 실행하겠다는 의미입니다.

그럼, shellArgs.windows 는 무엇이냐?

일단 Args는 Argument의 약자입니다.

> 쉘에서 사용자는 새로운 프로세스를 실행하면서 인자를 전달할 수 있습니다. 이처럼 프로세스를 실행하면서 전달하는 인자를 명령행 인자(Command Line Argument)라고 부릅니다.

아마 이걸 봐도 잘 와닿지 않으실거에요. 화학과의 입장으로써! 제가 이해한대로 Argument를 쉽게 말씀드리면 `git add {filename}`  이 명령어에서 add, {filename} 이 두가지도 모두 argument 입니다. 포괄적으로 보면, 어떤 명령어를 실행할 때 option을 붙여준다고 보시면 됩니다.

위에 shellArgs.window도 똑같습니다. 위에서 기본 터미널은 cmd로 설정해두었으니, 그 cmd를 열 때 어떤 argument를 주어서 shell을 실행하겠다는 것입니다. 그 때 shell 의 argument들을 list 형태로 묶어서 세팅하면 실행한다 는 의미입니다.

### 2-3. /K 가 도대체 뭘까?

![image](https://user-images.githubusercontent.com/54018187/106388041-04f79e80-6420-11eb-9358-0c756a08d5d3.png)

위의 사진은 여러분들의 cmd를 켜시고, 그대로 명령어를 치시면 `--help` argument 친 것 처럼 cmd 에 대한 help 설명이 나옵니다.

이 때, 우리가 주요깊게 봐야하는 부분은 바로 `/K` 부분입니다.

> 뒤에 string으로 되어있는 부분은 실행하되 session은 남긴다.

라는 의미입니다. 이 말은, cmd를 실행할 때,  /K Argument를 붙이고 뒤에 어떤 string을 붙이면, 그 string을 포함해서 cmd를 실행하되, session은 남긴다 라는 의미입니다. (session은 cmd를 끄지않고 그대로 둔다는 의미로 간단하게 이해하면 좋습니다.)

즉, **여러분이 cmd를 열 때, `cmd /K C:\anaconda3\Scripts\activate.bat C:\anaconda3` 를 실행한 채 session은 그대로 열어둔다.** 라는 의미입니다.

아마도 성준멘티님의 cmd에서 저 명령어 그대로 치면, 아마 아나콘다 프롬프트를 직접 키지 않더라도 바로 conda base가 실행되는 것을 볼 수 있을겁니다.

만약 성준멘티님이 파이썬 파일을 실행하기전에 base 말고 특정 가상환경으로 activate 하고 싶다하면,  `cmd /K C:\anaconda3\envs\{가상환경 명}\Scripts\activate.bat C:\anaconda3` 라고 하면 될 것 같습니다.

그래서 성준멘티님의 cmd를 아나콘다 prompt로 바꾼 것 같다는 말보다는 정확히 말하면, 아나콘다 프롬프트는 실행하지 않고도 cmd argument를 settings.json에 자동 저장해둠으로써 conda activate 를 할 수 있었다라고 말할 수 있을 것 같네요 ~~~

질문 있으면 꼭 댓글 달아주세요!

**Comment by yoomambo** [comment]
![image](https://user-images.githubusercontent.com/54018187/106389370-468b4800-6426-11eb-942b-3fbfb22b8828.png)

cmd에서 명령어 실행하면 바로 activate 되네요!

**Comment by NA-DK** [comment]
shell 의 argument들을 list 형태로 묶어서 세팅하면 실행한다 는 의미입니다.

-> 이 부분에서 list의 형태라는 말이 잘 이해가 가지 않습니다...!!ㅠㅠ

**Comment by yoomambo** [comment]
> shell 의 argument들을 list 형태로 묶어서 세팅하면 실행한다 는 의미입니다.
> 
> -> 이 부분에서 list의 형태라는 말이 잘 이해가 가지 않습니다...!!ㅠㅠ

```bash
"terminal.integrated.shellArgs.windows" : ["/K", "C:\\anaconda3\\Scripts\\activate.bat C:\\anaconda3"]
```

이 부분에서 대괄호를 의미합니다.

**Comment by lsj0822** [comment]
확인했습니다! 결국에 제가 구글링해서 찾은건 별도의 과정없이 바로 가상환경이 실행되게 만들어주는 코드였네요. 감사합니다!
