### ISSUE TITLE
[Python] 파일명, 클래스명, 함수명에 대해

### ISSUE THREAD

**Issue by ghost** [4Moyede/HexatonClass-01#177]
정말 간단한 질문이고 그냥 여러분의 생각이 궁금해서 여쭤봅니다.

코드 작업을 하다보니 하나의 .py 파일에는 연관있는 기능들만 모아놓는 것이 편하다는 결론이 났습니다.

문제는 그러다 보니 문제가 생겼습니다.

> 파일명 : 어떤 기능을 담고 있는 파일인지
클래스명 : 어떤 기능을 담고 있는 클래스인지
함수명 : 어떤 기능을 담고 있는 함수인지

이런 식으로 셋 다 이름이 비슷비슷해지는 역효과가 발생했습니다.

어떻게 하면 효과적으로 서로를 구분할 수 있을까요?

**Comment by dev-LeoKang** [comment]
하나의 python 파일에는 연관있는 기능들만 모아놓는 것은 아주 좋은 생각입니다!
이름에 관한 것은 다른 멘티분들 생각은 어떠실까요?
