### ISSUE TITLE
[GitHub] 이미 push한 commit에 파일을 추가하는 과정에서 생긴 문제

### ISSUE THREAD

**Issue by JaebeomHan** [4Moyede/HexatonClass-01#51]
**문제 발생**

- 실수로 하나의 파일을 add하지 않은 것을 push 후에 발견
- 나머지 파일 하나 (3번) 를 추가하고 싶은데 방법을 모름

**해결 과정**

- 진행했던 모든 단계를 중단하고 모두 삭제
- 재설치 및 처음부터 다시 단계 밟음
- 다시 세 개의 파일 모두를 add 한 후 commit 후 push 했으나 1, 2번 [파일은] 없고 3번 파일만 push됨
- branch를 삭제했다가 만들어도 보고 모든 commit 내역을 다 삭제도 해봄
- 이번엔 add 하려는데 'C:/Users/JaebeomHan/Documents/GitHub/HexatonClass-01/.git/index.lock': File exists. 라고 뜸
- 구글링 결과 HexatonClass-01 폴더에서 [보기] - [숨긴 파일 보기] 누르고 .git 폴더 들어가서 해당 파일 삭제함
- 파일들을 다시 add한 후 git status를 통해 확인 결과 changes to be committed 목록에 정상적으로 올라온걸 확인
- push 하려 했으나   ! [rejected]        S_JB -> S_JB (non-fast-forward)
error: failed to push some refs to 'https://github.com/4Moyede/HexatonClass-01.git 라는 오류 메시지 뜸

- https://devx.tistory.com/entry/git-push-%EC%8B%9C-%EC%98%A4%EB%A5%98%EB%A9%94%EC%84%B8%EC%A7%80-%EB%B0%9C%EC%83%9D%EC%9B%90%EC%9D%B8 이 글을 참고하여 git pull 명령을 해보았으나 해결 안 됨.
- git push --force 명령을 사용하였더니 기존 3번 파일만 있던 글에 1, 2번 파일이 추가된 것을 확인

**궁금한 점**

- 파일을 추가하는 방법
- index.lock 파일이 생성된 이유
- git pull 명령으로 해결이 안 된 이유

**Comment by yoomambo** [comment]
@JaebeomHan 멘티님 #28 혹시 commit을 분리해서 하는 방법 관련된 discussion 보셨나요?

**Comment by 4Moyede** [comment]
안녕하세요 @JaebeomHan 멘티님 형구 멘토입니다

현재 멘티님이 올린 궁금증 3가지는 2가지의 문제점에서 발생된 문제입니다

1. 이미 push 했던 commit에 새로운 파일을 추가하는 것은 불가능합니다
**local에서 새로 제대로 된 commit log를 만들어서** git push -f 혹은 git push --force를 하면, **기존에 있던 git log가 무시되고 이번에 push한 git log로 대체** 됩니다
만약 -f 옵션을 추가하지 않는다면 기존의 commit log와 지금 올리려는 log가 너무 다르기 때문에 reject가 발생하는 것입니다
그래서 사실 잘 못하면 이전의 했던 모든 것들이 사라질 수 도 있는 위험할수도 있는 작업입니다. 초기 단계라서 아무일 없이 잘 된 것 같습니다.

2. 모든 commit을 삭제하셨다고 하셨는데, 어떤 방식으로 했는지는 알 수 없지만 아마 git 자체의 오류가 발생하여 Deadlock이 발생한 것입니다.
명령어에 따른 작업이 시작하고 끝이 나야 다음 명령어를 실행하는데, 계속 명령어가 끝나지 않은 상태가 되어서 git add 명령어가 실행 되지 않은 것입니다.
원래 index.lock이라는 파일이 명령어가 끝이 나면 사라져야 하는데 삭제되지 않았고, 직접 삭제를 하고 나서야 Deadlock이 풀려 다음 명령어가 동작한 것이라고 예상합니다.

**Comment by yoomambo** [comment]
> 안녕하세요 @JaebeomHan 멘티님 형구 멘토입니다
> 
> 현재 멘티님이 올린 궁금증 3가지는 2가지의 문제점에서 발생된 문제입니다
> 
> 1. 이미 push 했던 commit에 새로운 파일을 추가하는 것은 불가능합니다
>    **local에서 새로 제대로 된 commit log를 만들어서** git push -f 혹은 git push --force를 하면, **기존에 있던 git log가 무시되고 이번에 push한 git log로 대체** 됩니다
>    만약 -f 옵션을 추가하지 않는다면 기존의 commit log와 지금 올리려는 log가 너무 다르기 때문에 reject가 발생하는 것입니다
>    그래서 사실 잘 못하면 이전의 했던 모든 것들이 사라질 수 도 있는 위험할수도 있는 작업입니다. 초기 단계라서 아무일 없이 잘 된 것 같습니다.
> 2. 모든 commit을 삭제하셨다고 하셨는데, 어떤 방식으로 했는지는 알 수 없지만 아마 git 자체의 오류가 발생하여 Deadlock이 발생한 것입니다.
>    명령어에 따른 작업이 시작하고 끝이 나야 다음 명령어를 실행하는데, 계속 명령어가 끝나지 않은 상태가 되어서 git add 명령어가 실행 되지 않은 것입니다.
>    원래 index.lock이라는 파일이 명령어가 끝이 나면 사라져야 하는데 삭제되지 않았고, 직접 삭제를 하고 나서야 Deadlock이 풀려 다음 명령어가 동작한 것이라고 예상합니다.

@JaebeomHan 멘티님 .git index.lock 에 대한 정보는 [git understand index.lock](https://www.pluralsight.com/guides/understanding-and-using-git's-index.lock-file)

**Comment by JaebeomHan** [comment]
@4Moyede 확인했습니다 ! -f 명령어는 실제 사용한다면 조심히 사용해야겠네요...
@yoomambo 글 잘 확인했습니다. 
The index.lock file prevents changes to your local repository from happening from outside of the currently running git process so as to ensure multiple git processes are not altering or changing the same repository internals at the same time.
git 자체에서 사용자의 실수를 방지하기 위해 제공하는 기능으로 이해했습니다
