### ISSUE TITLE
[GitHub] push 시 나타나는 403 에러

### ISSUE THREAD

**Issue by dlrudgnsdlek** [4Moyede/HexatonClass-01#54]
- 맨 처음에는 push를 했을 때 username 과 password를 치라고 해서 쳤더니 403에러가 떴습니다

- 403 에러를 찾아보니 권한 문제인 것 같아 키체인, 초기 사용자이름 지정 등등 구글링 해서 찾은 것들을 다 확인했습니다.

- 구글링으로 찾은 해결법 중 
git remote set-url origin https://github-username@github.com/github-username/github-repository-name.git
명령어를 입력하고
 GitHub-username : dlrudgnsdlek (본인계정)
GitHub-repository-name : HexatonClass-01 입력 후 git push origin S_GH 넣으면

- Repository not found. 라고 나옵니다..

- 저의 repositories에는 잘 올라갔는데,, 뭐가 문제인지 모르겠어요ㅠㅠ

**Comment by yoomambo** [comment]
안녕하세요. 멘티 유혁준입니다.

#22  이슈 확인하셨나요? 경훈 멘티님과 비슷한 오류라고 생각되는데요.
확인해보시고 다시 말씀해주세요

**Comment by yoomambo** [comment]
그리고 제가볼 때, 경훈 멘티님 How_to_use_push.pdf 나와있는대로 안하신 것 같습니다.

교재 다시 확인해보시고 교재에서 언급한대로 해주시길 바랄게요

**Comment by dlrudgnsdlek** [comment]
아 확인했습니다! 이슈 올리는 양식과 이 전 이슈들도 찬찬히 다시 살펴보겠습니다! 문제는 해결했습니다:) 감사합니다!
