### ISSUE TITLE
[GitHub] LF will be replaced by CRLF

### ISSUE THREAD

**Issue by lsj0822** [4Moyede/HexatonClass-01#72]
**Commit** : commit #70 
**Content** : 질문 내용에 대해서 서술하시오
```git bash
warning: LF will be replaced by CRLF in Mentee/LSJ/01/03_01_Answer1.ipynb.
The file will have its original line endings in your working directory
```
다음과 같이 commit하는 과정에서 파일을 add할때 다음과 같은 오류가 떴습니다.

파일을 올리는 것에는 이상이 없고, 해결책도 구글링으로 
https://jaddong.tistory.com/entry/git-add-%EC%97%90%EB%9F%AC-warning-LF-will-be-replaced-by-CRLF-%ED%95%B4%EA%B2%B0%EB%B0%A9%EB%B2%95
https://blog.jaeyoon.io/2018/01/git-crlf.html
https://dabo-dev.tistory.com/13

다음과 같이 autocrlf를 키라는 답변을 받았습니다.

그런데 다음과 같은 오류가 뜬 이유가 코딩과정에서 줄바꿈을 \n으로 해서 이런 오류가 뜬거같은데, 이는 LF에 해당해서 CRLF를 해야하는 환경에는 맞지 않는 것 같은데, 이것이 직관적으로 이해가 되지 않아 질문 올립니다

**Comment by 4Moyede** [comment]
사실 그냥 파일 잘 올라가니까 무시할수도 있을 법한 부분인데 정말 좋은 질문입니다!
**CR(Carrige Return, 타자기의 커서인 캐리지를 맨앞으로 되돌림)과 LF(Line Feed, 종이를 감아서 줄을 올림)은** 원래 타자기를 치던 때에 나온 말인걸 아셨나요?

![image](https://user-images.githubusercontent.com/38308646/103905239-b79a5100-5141-11eb-9d7f-a2a2b3d34733.png)

타자기를 쓸 때에 줄의 끝에 다다르면 타자기의 커서를 맨 앞으로 돌리고, 줄을 위로 한칸 감아야 합니다. 타자기는 CRLF를 해야 줄바꿈이 되는 것이죠.

저희가 기본으로 실습환경으로 사용하고 있는 **Windows 에서는 이 줄바꿈을 CRLF(\r\n)라고** 약속하고 있고, **Linux와 Mac에서는 줄바꿈을 LF(\n)라고** 약속하였습니다. 이제 타자기가 아니고 디지털화 된 장비이니까 캐리지를 앞으로 올릴 필요 없이 그냥 줄만 바꾸면 된다고 생각해서 그런 것 같아요. 그런데, 지금 우리는 Linux/Mac 의 방식대로 \n만 입력했으므로 **이 파일에 있는 \n(LF)를 \r\n(CRLF)로 바꿔서 줄바꿈을 제대로 표현할 수 있도록 해주는 것 입니다.**

실제로 제가 이전에 사용했던 Linux계열의 Ubuntu 에서나 현재 사용하고 있는 Mac 에서는 이러한 문제가 발생한 적이 없고, 저 또한 Windows 에서 동일한 메세지를 확인했었습니다.

**Comment by yoomambo** [comment]
@lsj0822 멘티님 혹시 확인하셨을까요?

확인하셨으면 멘토들이 확인할 수 있도록 답변 부탁드리겠습니다!

**Comment by lsj0822** [comment]
> @lsj0822 멘티님 혹시 확인하셨을까요?
> 
> 확인하셨으면 멘토들이 확인할 수 있도록 답변 부탁드리겠습니다!

앗 확인했습니다!
