### ISSUE TITLE
[GitHub] 이미 push까지 해버린 상태에서 add한 파일을 변경하는 방법

### ISSUE THREAD

**Issue by jiwoo4424** [4Moyede/HexatonClass-01#74]
**Content** : 주피터 노트북으로 작성한 파일을 저장하는 과정에서 .ipynb.url 형식으로 저장을 하였고 , 이 파일들을 add한 후 push까지 하였습니다. 그러다가 .ipynb버전으로 다시 올리고 싶어 기존 파일을 삭제하고 새로운 파일을 넣어준 뒤, how to push.pdf의 설명을 다시 보면서 이전과 같은 방식으로 add하고 push하는 과정에서 오류가 발생하였습니다. 이를 해결하고자 github에 다시 들어와서 pull request를 누르고 merge까지 해서 이전 파일들과 다시 넣은 파일들이 함께 저의 branch속으로 들어와 토론하고 검토하는 과정없이 파일이 올라가버렸습니다....... 

이를 통해서 저의 github 지식이 부족함을 느끼고 찾은 자료를 공유하고자 issue 란에 쓰는데 혹시 보완할 점이나 틀린 부분 댓글로 달아주시면 감사하겠습니다. 

1.  pull request 란?

GitHub 저장소에 Push된 소스 코드 변경 사항을 다른 개발자들에게 알리는 협업의 출발점입니다. 풀리퀘스트는 특정 브랜치에서 다른 브랜치로 적용하는 데 사용하고 특히 마스터 브랜치로 적용됩니다. 그리고 pull request가 생성이 되면 변경된 사항을 팀원들과 토론하고 검토할 수 있습니다. 이를 통해 특정 사용자에게 리뷰를 요청하거나 브랜치 보호 기능 설정으로 승인 프로세스를 적용할 수 있습니다.     

[출처] GitHub 기본 사용법 Webinar 4강 -Pull Request-\|작성자 단군소프트

2. branch의 개념

먼저 branch라는 뜻은 "나뭇가지" 라는 의미로 즉, 작업을 나뭇가지처럼 분할해서 처리한다는 것을 의미한다. 하나의 프로젝트를 
복사해서 branch를 만들고 분할 작업을 처리하고 크게 보면 작업이 끝난뒤 다시 병합하는 과정을 branch라 생각할 수 있다.
git으로 같이 공유하는 remote repository가 origin master라고 하고 내가 작업하는 공간은 master라고 한다. origin master를 clone하면 master branch가 생기고 테스트던 뭐던 어떤 용도를 위해서 또 다른 branch를 만들어 낼 수도 있다. ​그래서 작업하다가 commit을 하면 master branch로 commit이 되고 push하면 origin master로 올라가게 된다. 이 과정에서 충돌(conflict)이 나기도 한다. ​

그리고 항상 주의해야할 점은 push하기 전에 pull을 먼저 해야된다. 누가 변경한 사항이 있을 수 있으니 먼저 내 master에 남들이 수정한 내용이 먼저 적용된 후에 push해줘야 충돌이 줄어든다. ​pull을 하면 origin에 있는 것을 master로 받아온다. 

 [출처] Git, Github 개념 및 사용방법 (with SourceTree)\|작성자 하양

3.  merge란 ??

하나의 브랜치를 현재 브랜치와 합치는 것을 병합(merge)라고 합니다. 현재 브랜치는 헤드(HEAD) 브랜치라고 하며 예를 들어 헤드 브랜치가 master 이고 여기서 version2 브랜치를 병합하면 version2의 내용이 master에 반영되게 됩니다

**Comment by JaebeomHan** [comment]
어떤 오류가 발생했었는지 궁금하네요

**Comment by yoomambo** [comment]
@jiwoo4424 멘티님 이슈 등록 감사합니다.

멘티님께서 공부하시면서 서로 정보 공유하시려고 올리셔서 정말 칭찬하고싶습니다!

1. 저도 어떤 오류가 있었는지 궁금합니다. content에 제대로 된 문제 정의가 되어있지 않아 답변이 힘들 것 같아요.

2. pull request 란?, branch의 개념, merge란 ?? 공부하시면서 정리와 공유 목적으로 적어주셔서 정말 감사합니다. 저번에 수업 때 말씀드렸던 대로, issue는 어떤 문제가 생겼을시에 올리고, discussion은 주로 정보공유 목적으로 올립니다. 따라서 아래의 3가지 정리하신 부분들은 discussion에 자료공유 카테고리에 새로 올려주시길 바랍니다.

3. Content : 주피터 노트북으로 작성한 파일을 저장하는 과정에서 .ipynb.url 형식으로 저장을 하였고 , 이 파일들을 add한 후 push까지 하였습니다. 그러다가 .ipynb버전으로 다시 올리고 싶어 기존 파일을 삭제하고 새로운 파일을 넣어준 뒤, how to push.pdf의 설명을 다시 보면서 이전과 같은 방식으로 add하고 push하는 과정에서 오류가 발생하였습니다. 이를 해결하고자 github에 다시 들어와서 pull request를 누르고 merge까지 해서 이전 파일들과 다시 넣은 파일들이 함께 저의 branch속으로 들어와 토론하고 검토하는 과정없이 파일이 올라가버렸습니다.......

이 부분을 다음에 issue 등록할 때

## 과정 : 

1. 주피터 노트북으로 작성한 파일을 저장하는 과정에서 .ipynb.url 형식으로 저장을 하였음
2. 이 파일들을 add한 후 push까지 하였습니다. 
3. 그러다가 .ipynb버전으로 다시 올리고 싶어 기존 파일을 삭제
4. 새로운 파일을 넣어준 뒤, how to push.pdf의 설명을 다시 보면서 이전과 같은 방식으로 add하고 push

## 문제 : 

위의 과정들을 하는 중간에 

{어떤 오류가 났는지 설명}

이런 오류가 났었습니다.

## 시도 : 

1. 이를 해결하고자 github에 다시 들어와서 pull request를 누르고 
2. merge까지 해서 이전 파일들과 다시 넣은 파일들이 함께 저의 branch속으로 들어왔습니다.
3. 이 과정 속에서 토론하고 검토하는 과정없이 파일이 올라가버렸습니다.......

이런 방식으로 적어주셔야 할 것 같습니다.

@jiwoo4424 직접 issue 등록하신 부분 다른 사람들이 잘 알아볼 수 있도록 수정하시길 바랄게요!!!

**Comment by jiwoo4424** [comment]
![Alt text](/Documents/Github/KakaoTalk_20210107_160130381.png)

**Comment by 4Moyede** [comment]
오! commit의 am 옵션에 대해서 공부하셨네요!
git에서 파일의 상태에 대해 정리하여 Discussion에 올릴테니 확인하세용

**Comment by JaebeomHan** [comment]
> <img alt="KakaoTalk_20210107_160130381" width="413" src="https://user-images.githubusercontent.com/76776979/104054685-e6dbbb80-5230-11eb-8314-056d693eee9d.png">
> 
> 이런 메세지가 떠가지고 그림에 나와있는 rm을 써서 파일을 삭제하고 해결했습니다 !
> 
> <삭제시>
> 
> Git rm 파일
> Git commit -am ‘알려줄 내용’
> Git push -u origin master
> 
> 이를 사용하면 파일 삭제후 변경사항을 push 가능합니다 !! 이미 알고 계실지도 모르지만 혹시 모르신다면 참고하셔서 도움되셨으면 좋겠어요 ...

git push -u origin master 면 master branch에 바로 push하는건가요?

**Comment by yoomambo** [comment]
> <img alt="KakaoTalk_20210107_160130381" width="413" src="https://user-images.githubusercontent.com/76776979/104054685-e6dbbb80-5230-11eb-8314-056d693eee9d.png">
> 
> 이런 메세지가 떠가지고 그림에 나와있는 rm을 써서 파일을 삭제하고 해결했습니다 !
> 
> <삭제시>
> 
> Git rm 파일
> Git commit -am ‘알려줄 내용’
> Git push -u origin master
> 
> 이를 사용하면 파일 삭제후 변경사항을 push 가능합니다 !! 이미 알고 계실지도 모르지만 혹시 모르신다면 참고하셔서 도움되셨으면 좋겠어요 ...

@jiwoo4424 

```bash
git push -u origin master
```

이 부분에서 branch 명이 master로 되어있는데, 혹시 다른 곳에서 복사 붙여넣기하면서 main으로 안바꾸신건가요?

**Comment by yoomambo** [comment]
> > <img alt="KakaoTalk_20210107_160130381" width="413" src="https://user-images.githubusercontent.com/76776979/104054685-e6dbbb80-5230-11eb-8314-056d693eee9d.png">
> > 이런 메세지가 떠가지고 그림에 나와있는 rm을 써서 파일을 삭제하고 해결했습니다 !
> > <삭제시>
> > Git rm 파일
> > Git commit -am ‘알려줄 내용’
> > Git push -u origin master
> > 이를 사용하면 파일 삭제후 변경사항을 push 가능합니다 !! 이미 알고 계실지도 모르지만 혹시 모르신다면 참고하셔서 도움되셨으면 좋겠어요 ...
> 
> git push -u origin master 면 master branch에 바로 push하는건가요?

![image](https://user-images.githubusercontent.com/54018187/104120866-74c4bd00-537d-11eb-8387-7a1d83b1b0bf.png)

@jiwoo4424 @JaebeomHan 

1. T_HJ branch에서 파일을 수정한 후, add, commit 완료
2. T_HJ branch에서 main으로 `git push -u origin main`
3. T_HJ에서 main으로 push가 되지 않음.

## 원인 분석 

local main이 아닌 local branch에서 remote main으로 push를 하면?

**git가 `git push -u origin main` 에서 `main`을 인식해서 local main branch에서 remote main으로 push를 하는 것입니다.**

저는 local main에서는 어떠한 파일도 수정을 하지 않았으니, 
```bash
Everything up-to-date
Branch 'main' set up to track remote branch 'main' from 'origin'.
```
모든 것이 up to date라는 라는 출력물이 떴던 것이죠!

자세한 부분은 [git push에 관련된 사이트 원본](https://git-scm.com/docs/git-push)을 보시길 바랍니다.

## 결론?

다른 branch로 push를 하고 싶으면 git checkout으로 넘어가서
해당 local branch에서 수정하고 해당 remote branch로 push를 진행하면 좋을 것 같아요.

**Comment by 4Moyede** [comment]
@JaebeomHan 궁금하신 점이 해결 되었나요?

**Comment by JaebeomHan** [comment]
> @JaebeomHan 궁금하신 점이 해결 되었나요?

@4Moyede @yoomambo 

~~아주 죽을 맛이네요~~

저 사실 remote랑 local 이랑 pull request가 왜 생기는건지 혼란스럽습니다 구글링좀 해볼게요

**Comment by 4Moyede** [comment]
ㅎㅎ구글링해보셨나요? 검색해서 내리신 결론 공유 부탁드립니다

**Comment by jiwoo4424** [comment]
> > @JaebeomHan 궁금하신 점이 해결 되었나요?
> 
> @4Moyede @yoomambo
> 
> ~아주 죽을 맛이네요~
> 
> 저 사실 remote랑 local 이랑 pull request가 왜 생기는건지 혼란스럽습니다 구글링좀 해볼게요

이 issue는 이제 close할테니 검색해서 내리신 결론 공유는 discussion에 부탁드립니다 ~!~!
