### ISSUE TITLE
[Python]  2번 문제 중, elif 부분 코드 리뷰 가능할까요?

### ISSUE THREAD

**Issue by 4Moyede** [4Moyede/HexatonClass-01#77]
**Commit** : b403c32884936dcb7f174546b34672b0b0bcc130
**Content** : 2번 문제의 elif의 조건문에 대해서 설명해주실 수 있나요?
![image](https://user-images.githubusercontent.com/38308646/103901512-97b45e80-513c-11eb-8f9d-6d97a0e287fd.png)

**Comment by dlrudgnsdlek** [comment]
if num > 1000000000  부분이여??

**Comment by 4Moyede** [comment]
궁금한 코드 부분 캡처해서 수정하였습니다

**Comment by dlrudgnsdlek** [comment]
문제 조건에서 21억 이하의 수의 역도 21억 이하가 돼야 한다고 했고, 10억 이상의 수를 입력하면 그 수의 역은 21억이 넘을 수도 있기 때문에 (예를 들어 10억9를 거꾸로하면 90억10) 100과 10으로 나눈 나머지를 통해서 그 수의 역이 21억이 안넘게 했습니다

**Comment by 4Moyede** [comment]
continue를 만나면 다음은 어디가 실행이 될까요?

**Comment by dlrudgnsdlek** [comment]
continue를 만나면 실행되는게 없는것 같아요.. continue가 없어도 될 것 같습니다.

**Comment by 4Moyede** [comment]
맞습니다! continue를 만나면 사실 말 뜻이 '계속'이라는 뜻이라 밑으로 내려갈 것 같지만 for문에서 부터 다시 시작입니다.
원하시는 효과를 얻으려면

```python
else:
    pass
```

라고 쓰시거나, else문을 지우시면 해결 될 것입니다.

과제하느라 고생하셨습니당
