### ISSUE TITLE
[GitHub] pull request 까지 진행한 후에 갑자기 파일을 빼고 싶다?

### ISSUE THREAD

**Issue by JaebeomHan** [4Moyede/HexatonClass-01#90]
#### **Content**
@jiwoo4424 님께서 여쭤보셨는데 저도 확실한 지식이 없으니 멘토님들의 조언 부탁드립니다...!!
* * *
이건 여담인데 브랜치 설명에 .py 파일을 삭제하고 새로 올렸다고 했는데 이미 push하고 pull request 된 파일들을 삭제한 것인가요 ??? 맞다면 어떻게 삭제하는지 방법들을 혹시 issue나 discussion에 올려주실 수 있나요 ?? 너무 궁금합니다 !!
* * *
라고 여쭤보셨는데 아마 제 기억으로는 pull request 까지 된 상태에서 push 한 파일 중에 .py 파일을 빼기 위해 제 local 폴더에서 해당 파일들을 삭제하였고 파일을 삭제했다는 변경 내역을 commit 후에 push 하였습니다.

pull request에서 제 commit 내역을 보면 라벨을 신경 안쓴 거 빼고는 제 생각대로 정상적으로 올라가 있습니다.

저번에 Git bash 로 고생했던 날 파일 추가든 삭제든 commit 만 잘 해서 push 하면 되겠다고 생각했는데 혹시 제 생각이 틀렸거나 문제가 있다면 조언 부탁드립니당

**Comment by 4Moyede** [comment]
파일 추가와 삭제에 대해 commit 메세지를 잘 남긴다면 괜찮다고 생각은 합니다.

만약에 실수로 추가 했던 파일이 **보안상 문제가 있다거나 개인적인 파일**이라면, 파일을 삭제해도 그 파일이 존재했던 시기로 돌아가서 다시 볼 수 있기 때문에 문제는 될 것 같습니다. 그런 경우는 reset 명령어를 통해 다시 뒤로 돌아가서 다시 add, commit 해야겠지요!

Discussion에 git의 파일의 상태에 대한 정리 올려두겠습니다

**Comment by JaebeomHan** [comment]
> 파일 추가와 삭제에 대해 commit 메세지를 잘 남긴다면 괜찮다고 생각은 합니다.
> 
> 만약에 실수로 추가 했던 파일이 **보안상 문제가 있다거나 개인적인 파일**이라면, 파일을 삭제해도 그 파일이 존재했던 시기로 돌아가서 다시 볼 수 있기 때문에 문제는 될 것 같습니다. 그런 경우는 reset 명령어를 통해 다시 뒤로 돌아가서 다시 add, commit 해야겠지요!
> 
> Discussion에 git의 파일의 상태에 대한 정리 올려두겠습니다

갑자기 든 생각인데 _reset_ 명령어를 실제로 사용하는 예시를 보여주시면 (라이브로 보여주시면 더더욱) Git 실력에 큰 도움이 될 것 같습니다. 실제로 과제 하다가 _reset_ 을 사용할 상황이 왔을 때 ~~(있을진 모르겠지만)~~ 당황하지 않고 유연하게 대처하고 싶습니다.

**Comment by 4Moyede** [comment]
다음 수업에 라이브로 보여드리겠습니다!

**Comment by JaebeomHan** [comment]
> 다음 수업에 라이브로 보여드리겠습니다!

감삽니다~~~!!
